/*
	Autor : Erik Niebla A.
	Mail: 	ep_niebla@hotmail.com,ep.niebla@gmail.com
	Fecha: 	08/08/2015
*/
$(document).ready(function(){
    $(window).on('load',function(){
        $(".radioset").buttonset();
        $('input.hasDatepicker:not(.hasTimepicker):not(.isTimepicker)').attr({placeholder:'yyyy-mm-dd',pattern:$.getDateRegExp()});
        $('input.isTimepicker').attr({placeholder:'hh:mm',pattern:$.getHoraRegExp()});
        $('input.hasTimepicker').attr({placeholder:'yyyy-mm-dd hh:mm',pattern:$.getDateRegExp()+' '+$.getHoraRegExp()});
        $('input.numeric,input.decimal').setValidateNum();
        if(!$.isUnd($.mask)){
            $('input.hasDatepicker:not(.hasTimepicker):not(.isTimepicker)').mask("9999-99-99",{placeholder:"_"});
            $('input.hasTimepicker').mask("9999-99-99 99:99",{placeholder:"_"});
            $('input.isTimepicker').mask("99:99",{placeholder:"_"});
        }
        $(document).tooltip({/*items:":not(.noTooltip)",*/content:function(){return $(this).attr('title');},track:true});
        $('input.msgInvalid').each(function(i,v){ var m=$(v).data('msg'); if(m!==undefined) $(v).attr({oninvalid:"setCustomValidity($(this).data('msg'));",oninput:"setCustomValidity('');"});});
        $('input.onEnter').each(function(i,v){ $(v).attr('onkeydown','ejecutaOnEnter.call(this,event,this.value);'); });
    });	//$(".isSelectMenu").selectmenu();//$(".isMoney").MoneyFormat("33334");
});
// FUNCIONES JQGRID 5.1 JQUERY
$.onEv=function(t,r,c){var f=false,a=['onNumeric','onIsNaN','onPasteInput']; if($.isText(t)){a.push(t);t=a.length-1;} return !$.isUnd(a[t])?(r!==f?'return ':'')+a[t]+(c!==f?'.call(this,':'(')+'event);':'';};
$.fn.setValidateNum=function(){this.each(function(i,e){ var t=$(e),p='placeholder'; t.attr({onkeypress:$.onEv(0),onkeyup:$.onEv(1,!0),onpaste:$.onEv(2,!0)}); if(!$.isUnd(t.data('decimals'))&&$.isUnd(t.attr('decimals'))) t.attr('decimals',t.data('decimals')); if(!$.vv(t.attr(p))) t.attr(p,$.vv(t.attr('decimals'))?'0.00':0); }); };
$.newObj=function(a,o,def){var no=def||{}; if($.isArray(a)) $.each(a,function(i,v){ if($.isObj(v)) $.extend(no,$.cloneData(v)); else no[v]=$.cloneData(o[v]); }); return no; };
$.funcOrVal=function(d,arg,def,inside){ if(!$.isBool(inside))inside=false; return $.vv(d)?($.isFunc(d)?($.vv(arg)?d(arg):d()):(inside&&$.isObj(arg)?arg[d]:d)):def; };
$.getFunction=function(f){var u; return $.isFunc(f)?f:($.isText(f)?($.isset(f)&&$.isFunc(eval(f))?eval(f):u):u);};
$.unformatCellData=function(cv,opts,el){ return $(el).find('div').data('originaldata'); };
$.unformatCellHtml=function(cv,opts,el){ var e=$(el),c=$(e.prop('firstChild')).not('.btn'); var i=c.find('input[role=textbox],select[role=select]'); if(i.length===1) c=i; return c.is(':input')?c.val():e.text(); };
$.numFormat=function(val,type){ if(!$.vv(type))type='currency'; return $.fn.fmatter(type, val*1,$.jgrid.regional["es"].formatter); };
$.numUnformat=function(val,type){ if(!$.vv(type))type='currency'; return $.unformat($("<span>"+val+"</span>"),{colModel:{formatter:type,formatoptions:$.jgrid.regional["es"].formatter[type]}})*1; };
$.fn.numFormat=function(type){var f=this.is(':input')?'val':'html'; this[f]($.numFormat(this[f](),type)); return this; };
$.fn.numUnformat=function(type){var f=this.is(':input')?'val':'html'; this[f]($.numUnformat(this[f](),type)); return this; };
$.groupHeader=function (cellval,opts,rowObject,action){
    var dato=cellval, groupIdPrefix=opts.gid+"ghead_", groupIdPrefixLength=groupIdPrefix.length,name=opts.colModel.name,span=opts.colModel.groupSpan, gspan=(($.vv(span)&&span!=='')?span=span.replace(/{0\}/gmi,cellval):cellval),fields=span.match(/([^{]*?)\w(?=\})/gmi);
	if(opts.rowId.substr(0,groupIdPrefixLength)===groupIdPrefix&&$.isUnd(action)){ var data=$('#'+opts.gid).jqGrid("getGridParam", "data")/*getSeletedByComlumn(name,cellval)*/,item,count=0; $.each(data, function(i,v){ if(v[name]===cellval){ if(!$.vv(item))item=v; count++;  } }); gspan=gspan.replace(/{1\}/g,count); if($.vv(fields)) $.each(fields, function(i,v){ if($.vv(item[v])&&isNaN(v)){gspan=gspan.replace(new RegExp('{'+v+'\}','g'), item[v]); } });gspan=gspan.replace(/{\w\}/g,''); return gspan; } return dato;
};
$.originalRow=function(name){ return $.extend({},$.originalDataRow,{name:(name||'OriginalData')}); };
$.originalDataRow={label:'',name:'OriginalData',hidden:true,viewable:false,editable:false,width:0,title:false,formatter:function(cv,opts,rObj){ return $("<div/>").attr('data-originaldata',$.jsonParser($.cloneCO(opts,rObj))).hide().prop('outerHTML'); },unformat:$.unformatCellData };
$.fn.pk=function(){ return this[0].p.keyName; };
$.fn.getOriginalData=function(id,name){if($.vv(id)) return this.jqGrid('getCell',id,(name||'OriginalData')); else return this.getGridColumn((name||'OriginalData'));};
$.fn.getColModel=function(name){ var c; $.each(this[0].p.colModel,function(i,v){ if(v.name===name){ c=v; return false; } }); return c; };
$.fn.gridColUpdate=function(type,cols,resize){ if(this.length>0&&$.inArray(type,['show','hide'])<0||!$.vv(cols)) return this; var b=$.isBool(resize)?resize:true,t=this,w=t[0].p.width; if($.isText(cols))cols=[cols]; $.each(cols,function(i,v){ t[type+'Col'](v); }); if(b){t.setGridWidth(w); t[type+'Col'](cols[0]);} return t; };
$.fn.gridUpdate=function(page){this.trigger('reloadGrid',[{page:$.vv(page)?page:($.vv(this[0])&&$.vv(this[0].p)?this[0].p.page||1:1)}]); return this;};
$.fn.loadUpdate=function(){ var g=!!this.length?this[0].p:null,dt={total:g.lastpage,page:g.page,records:g.records,rows:g.data,userdata:g.userData};  if($.vv(g)){ this.triggerHandler("jqGridLoadComplete", [dt]); if($.isFunc(g.loadComplete)) g.loadComplete.call(this,dt); this.triggerHandler("jqGridAfterLoadComplete", [dt]); } return this; };
$.fn.nextIndex=function(col){ col=$.vv(col)?col:'index'; var next=this.jqGrid('getCol',col,false,'max'); return (isNaN(next)?1:next+1); };
$.fn.getCaption=function(div){var d=$($(this)[0].grid.cDiv).find('.ui-jqgrid-title'); return div?d:d.html();};//Return boolean
$.fn.getIndexById=function(id){var ids=this.jqGrid('getDataIDs');for (var i=0; i<ids.length; i++){if(ids[i]===id) return i;}return -1;};//Return int
$.fn.clearGrid=function(footer){ var t=this;  if(!$.vv(t)||t.length===0) return;  t.jqGrid('setGridParam',{datatype:'local'}); t.jqGrid("clearGridData",($.vv(footer)&&footer===true)); return t.jqGrid('setGridParam',{data:[]}).gridUpdate(1); };
$.fn.setRow=function(r){ var t=this,i=t.pk(); if(!$.isObj(r)||!$.vv(r[i])) return t; t.jqGrid('addRowData',r[i],r,'last'); var p=t[0].p.data.length-1; if($.vv(t[0].p.data[p]) && t[0].p.data[p][i]===r[i]) $.extend(t[0].p.data[p],r); t.highlightRow(r[i]); t.triggerHandler('jqGridAfterLoadComplete',{rows:[r]}); return t; };
$.fn.setRows=function(rows){ this.clearGrid(); if(!$.vv(rows)||!rows.length) return this; return this.jqGrid('setGridParam', {datatype:'local',data:rows,records:rows.length,total:1}).gridUpdate(1); };
$.fn.setRowsByIndex=function(rows,index){ if($.isArray(rows)) for(var i=0;i<rows.length;i++) rows[i][$.vv(index)?index:'index']=i; return this.setRows(rows); };
$.fn.getColumnIndexByName=function(col){var cm=this.jqGrid('getGridParam', 'colModel'),i,l; for(i=0,l=cm.length;i<l;i+=1){if(cm[i].name===col) return i;};return -1;};
$.fn.existsId=function(id){var ids=this.jqGrid('getDataIDs');for (var i=0; i<ids.length; i++){if(String(ids[i])===String(id)) return true;}return false;};//Return boolean
$.fn.existsValByCol=function(col,value){ if(this.getColumnIndexByName(col)===-1) return false; var ids=this.jqGrid('getDataIDs'); for (var i=0; i<ids.length; i++){if(String((this.jqGrid('getRowData', ids[i]))[col])===String(value)) return true;}return false;};//Return boolean
$.fn.selectAllByCol=$.fn.selectAllByComlumn=function(col,marca,formatter){ formatter=($.vv(formatter)?formatter:false); marca=($.vv(marca)?marca:true);var ids=this.jqGrid('getDataIDs'),ban=""; if(marca){ban="Yes";}else{ban="No";}; for(var i=(ids.length-1);i>=0;i--){ if(formatter){ var sett={[col]:marca}; this.changeRow(ids[i],sett); }else this.jqGrid('setCell',ids[i],col,ban);}; return this; };
$.fn.getSelectedByCol=$.fn.getSeletedByComlumn=function(col,marca,allFields){ var idName=this.pk() ,batch=new Array(),ids=this.jqGrid('getDataIDs');marca=($.vv(marca)?marca:'Yes');allFields=($.vv(allFields)?allFields:true);	for (var i=0; i<ids.length; i++){ this.jqGrid('saveRow',ids[i],false,'clientArray'); var data=this.jqGrid('getRowData',ids[i]); if(String(data[col])===String(marca)){ if(allFields){ if(!$.vv(data[idName])) data[idName]=ids[i]; batch.push(data);}else batch.push(ids[i]); } } return batch; };
$.fn.getGridColumn=function(col){ var batch=new Array(),cols=new Array(); if(!$.vv(col))return batch; var ids=this.jqGrid('getDataIDs');
	if($.isArray(col)){ for(var j=0;j<col.length;j++){ var i=this.getColumnIndexByName(col[j]); if(i>=0) cols.push({i:i,k:col[j]}); } if(!cols.length) return batch; for(var i=0,z=ids.length;i<z;i++){ var item={}; for(var j=0;j<cols.length;j++){item[cols[j]['k']]=this.jqGrid('getCell',ids[i],cols[j]['i']);} batch.push(item); } } else{ if(this.getColumnIndexByName(col)===-1) return batch; for(var i=0,z=ids.length;i<z;i++){ batch.push(this.jqGrid('getCell',ids[i],col)); } } return batch;
}; //return array
$.ocf=function(o){return o.colModel.formatoptions||{};};
$.caseFalse=function(ca,ob){ var result=''; if($.isArray(ca)) $.each(ca,function(i,v){ if($.vv(v['col'])){ var ban; try{ ban=eval("'"+ob[v['col']]+"'"+v['eval']); }catch(e){ ban=false; }; if(ban){ result=v['value']||$.createIcon(v['icon'],0,$.vv(v['title'])?'title="'+v['title']+'"':''); if(result==='') result=' '; return false; } };  }); return result; };
$.fn.validCols=function(c){ if($.isArray(c)) for(var i=(c.length-1);i>=0;i--){ if(this.getColumnIndexByName(c[i])<0) c.splice(i,1); } else c=$.isText(c)&&this.getColumnIndexByName(c)>-1?[c]:[];  return c; };
$.fn.getFootRow=function(noBorder){ var id=this.attr('id'), fRow=$("#gbox_"+id+" #gview_"+id+" .ui-jqgrid-sdiv .footrow"); if(noBorder===true) fRow.find('>td:not(.jqgrid-rownum)').filter(function(){ return $(this).css('display').length>0; }).addClass('bgNoColor').removeClass('ui-state-default').addClass("bgNoRight").filter(function(){ return $(this).css("display")!=="none"; }).last().removeClass('bgNoRight'); return fRow; };
$.fn.clearFootRow=function(except){ var e=$.isArray(except)?except:[except],t=this,f=t.getFootRow(true); $.each(e,function(i,v){ f.find('>td[aria-describedby="'+t.attr('id')+'_'+v+'"]').removeClass('bgNoColor bgNoRight').prev().removeClass('bgNoRight');  }); return t; };
$.fn.getGridSummary=function(cols){ var o={},t=this, cols=t.validCols(cols); $.each(cols,function(i,v){ var p=t.getColumnIndexByName(v); o[v]=t.jqGrid('getCol',v,false,t[0].p.colModel[p]['summaryType']||'sum'); }); return o; };
$.fn.setGridSummary=function(cols,item,format,ffunc){ var t=this, c=t.validCols(cols), f=format; if(c.length===0) return this; if(!$.isObj(item))item={}; $.extend(item,t.getGridSummary(c)); if(!$.vv(f)||f===true) t.jqGrid('footerData','set',item); else{  $.each(item,function(k,v){ var ft=$.isBool(f)?f:$.inArray(k,f)===-1; t.jqGrid('footerData','set',{[k]:!ft&&$.isFunc(ffunc)?ffunc(v):v},ft); }); }return this; };
$.fn.startGridEdit=function(wh){var aux=$.jgrid.inlineEdit; $.jgrid.inlineEdit={focusField:false}; var ids=this.jqGrid('getDataIDs'); for(var i=(ids.length-1); i>=0 ; i--){if(!$.isFunc(wh)||wh(this.jqGrid('getRowData',ids[i])))this.jqGrid('editRow',ids[i]);} $.jgrid.inlineEdit=aux;  return this; };
$.fn.stopGridEdit=function(){var ids=this.jqGrid('getDataIDs'); for (var i=0; i<ids.length; i++){this.jqGrid('saveRow',ids[i],false,'clientArray');} return this; };
$.fn.changeRow=function(rowId,data,defaults,replaceEdit){ if(!$.vv(rowId)||!$.isObj(data)) return; if(!$.isObj(defaults)) defaults={}; var inputs; if($.isObj(replaceEdit)){ inputs=replaceEdit; replaceEdit=true; } if(!$.isBool(replaceEdit))replaceEdit=false; var t=this,edit=t.find('tr#'+rowId).attr('editable')*1?1:0,edit_fields=(edit?t.find('tr#'+rowId).getDataForced():{}),editing=($.extend(defaults,edit_fields)),new_data={};if(t[0].p.datatype==='local') new_data=$.extend(t.jqGrid('getLocalRow',rowId),data,editing,inputs||{}); else new_data=$.extend(new_data,t.jqGrid('getRowData',rowId),data,editing,inputs||{}); var aux=$.extend(true,{},new_data); if(!replaceEdit){ $.each(edit_fields,function(k,v){delete aux[k];}); t.jqGrid('setRowData',rowId,aux); }else{ if(edit){ if($.isObj(inputs)) t.find('tr#'+rowId).setData(new_data,false);  t.jqGrid('saveRow',rowId, false, 'clientArray'); } t.jqGrid('setRowData',rowId,new_data); if(edit)t.jqGrid('editRow',rowId); } t.triggerHandler('jqGridAfterLoadComplete',{rows:[new_data]}); return new_data; };
$.fn.changeRowData=function(rowId,data,opts){ if(!$.vv(rowId)||!$.isObj(data)) return; var t=this,opts=opts||{}, defaults=$.extend(true,{},opts.defaultChangeRow||t[0].p.defaultChangeRow||{}), newD=$.extend(true,{},$.extend(/*t[0].p.datatype==='local'?t.jqGrid('getLocalRow',rowId):*/t.jqGrid('getRowData',rowId),defaults) ), ex=[].concat(opts.excludeChangeCols||t[0].p.excludeChangeCols||[]); $.each(ex,function(k,v){delete newD[k];}); $.extend(newD,data); t.jqGrid('setRowData',rowId,newD); if(opts.trigger===true||$.isUnd(opts.trigger)) t.triggerHandler('jqGridAfterLoadComplete',{rows:[newD]}); return t; };
$.fn.setGridNoPager=function(){$(this.setGridParam({rowNum:10000000,pgbuttons : false,pgtext : "",pginput : false}).getGridParam('pager')).find('td[id$=Pager_center]').hide(); /*this.gridUpdate();*/ return this;};
$.fn.colspanFooter=function(col,span){ if(!$.vv(col)||this.getColumnIndexByName(col)===-1||!$.isNum(span)) return this; var f=this.closest(".ui-jqgrid-bdiv").next(".ui-jqgrid-sdiv").find(".footrow"), ci=f.find('>td[aria-describedby="'+this.attr('id')+'_'+col+'"]'), cols=[], wi=ci.width(), w=0; for(var i=0; i<(span*1)-1;i++){ var cai=i-1>-1?cols[i-1]:ci; var e=cai.next(); w+=e.outerWidth(); cols.push(e); } $.each(cols,function(i,v){ v.hide(); }); ci.attr("colspan",span).width(wi+w); return this; };
$.fn.getGridBatch=function(wh){ var t=this, idName=t.pk(), batch=new Array(),cond=($.isFunc(wh)),ids=t.jqGrid('getDataIDs'); t.unHighlightSearch(); for (var i=0; i<ids.length; i++){ if(t.find('tr#'+ids[i]).attr('editable')*1) t.jqGrid('saveRow', ids[i], false, 'clientArray'); var rda=t.jqGrid('getRowData', ids[i]); if(!$.vv(rda[idName])) rda[idName]=ids[i]; if(!cond||wh(rda)) batch.push(rda); } return batch; }; //return array
$.fn.updateGridsSizes=function(){ this.find('[id^="gbox_"]').each(function(index){  var $this=$(this); if($this.actual('width')<=150){ var id=($this.attr('id')).split('_'); id.splice(0,1); id=id.join('_'); $('#'+id).jqGrid("resizeGrid"); } }); return this;};
$.getGridButton=function(action,data,title,icon,text,type,size,attr,icon2){ var a=action,d=data; if($.isObj(a)){ title=a['title'];icon=a['icon'];icon2=a['icon2'];text=a['text'];type=a['type'];size=a['size'];attr=a['attr'];d=a['data'];a=a['action']; } var b=$('<button type="button" onclick="" class="btn btn-'+($.vv(type)?type:'success')+' btn-'+($.vv(size)?size:'xs')+'">'+(icon===''?'':$.createIcon($.vv(icon)?icon:'arrow-right'))+(icon2===''||!$.vv(icon2)?'':'&nbsp;'+$.createIcon(icon2))+($.vv(text)?' '+text:'')+'</button>'),click; if($.vv(a)&&$.vv(d)){ click=$.isFunc(a)?a.name:a; if(click.indexOf('(')===-1&&click.indexOf(')')===-1) click+="($.cloneData($(this).data('originaldata')))"; } b.attr($.extend({title:$.vv(title)?title:($.vv(text)?text:'Seleccionar'),'onclick':click,'data-originaldata':$.jsonParser(d)},$.isObj(attr)?attr:{})); return b.prop('outerHTML'); }; //return string
$.fn.gridButtonsAdd=function(array){ var $t=this; if(!$.isArray(array)) return $t; $.each(array,function(i,v){ $t.gridButtonAdd(v); }); return $t; }; /*individual*/ $.fn.gridButtonAdd=function(opts){ if(!$.vv(opts))opts={}; if(!Object.keys(opts).length) opts={sepclass:'ui-separator'}; if($.vv(opts['sepclass'])) this.jqGrid('navSeparatorAdd',this[0].p.pager,$.extend({sepclass:'ui-separator',sepcontent:''},opts)); else{ if($.vv(opts['buttonicon']))opts['buttonicon']=$.createIcon(opts['buttonicon'],true); opts['caption']=$.vv(opts['caption'])?'&nbsp;'+opts['caption']:''; this.jqGrid('navButtonAdd',this[0].p.pager,$.extend(true,{position:"last"},opts)); } return this; };
$.fn.setCellEv=function(ev){var t=this; if($.isObj(ev)) $.each(ev,function(k,v){ var fun=$.isFunc(v)?"($('#'+$(this).data('gid')).getColModel($(this).data('name')))['formatoptions']['dataEvents']['"+k+"']":$.isText(v)?v:null; if($.vv(fun)) t.attr('on'+k,(t.attr('on'+k)||'')+fun+(fun.indexOf('(')===-1&&fun.indexOf(')')===-1?".call(this,$(this).data(),$('#'+$(this).data('gid')).jqGrid('getRowData',$(this).data('rowId')));":'')); }); return t;};
$.fn.fmatter.textboxExa=function(cv,opts,cObjt){return $.createFmatter(cv,opts,cObjt,'input');}; $.fn.fmatter.textboxExa.unformat=$.unformatCellHtml;
$.fn.fmatter.selectExa=function(cv,opts,cObjt){return $.createFmatter(cv,opts,cObjt,'select');}; $.fn.fmatter.selectExa.unformat=$.unformatCellHtml;
$.fn.fmatter.truefalse=function(cv,opts,cObjt){ var f=$.ocf(opts),yv=f['yesValue'],v=$.vv(yv)?($.isFunc(yv)?yv(cv):yv===cv):$.toBool(cv),e=v?'yes':'no',msgVar=e+'Msg',micon=e+'Icon',mcolor=e+'Color',msg=''+$.funcOrVal(f[msgVar],cObjt,v?'Si':'No'), icon=$.funcOrVal(f[micon],cObjt,v?'ok':'remove'), color=$.funcOrVal(f[mcolor],cObjt,v?'green':'blue'); if(!$.isBool(f['msg'])) f['msg']=true; return (!$.vv(cv)||cv===''?'':$('<div><i/>'+(!f['noText']?'<u class="hidden">'+cv+'</u>':'')+'</div>').attr({'data-originaldata':cv,title:f['msg']?msg.trim():''}).find('i').attr('class',$.createIcon(icon,true)+' '+color).end().prop('outerHTML')); }; $.fn.fmatter.truefalse.unformat=$.unformatCellData;
$.fn.fmatter.checkboxExa=function(cv,opts,cObjt){ var o=cObjt,f=$.extend({yes:'S',no:'N'},$.ocf(opts)),con=$.getFunction(f['conditional']),id=opts.rowId,c=opts.colModel,n=f['name'],i=$.getFunction(f['dataInit']); if(($.isFunc(con)&&!con(o))||($.vv(f['nullifField'])&&o[f['nullifField']]!==(f['nullifValue']||''))||(f['nullif']===true&&(!$.vv(cv)||cv===(f['nullifValue']||'')))) return ''; var el=$('<input />').attr({'id':id+"_"+c.name,type:"checkbox",name:$.vv(n)?(n===true?c.name:n):undefined,rowid:id,/*'data-gid':opts.gid,'data-name':c.name,'data-row-id':id,*/value:f['yes'],offval:f['no'],checked:(cv===f['yes']||(!(!$.vv(cv)||cv==='')&&f['defaultChecked']===true)),onchange:f['onchange']}); $.extend(el[0].dataset,{gid:opts.gid,rowId:id,name:c.name,pos:opts.pos}); if($.isFunc(i))i(el[0],opts,o); el.setCellEv(f['dataEvents']); return el.prop('outerHTML'); }; $.fn.fmatter.checkboxExa.unformat=function(cv,opts,el){ var f=$.ocf(opts); var ckb=$(el).find('input[type=checkbox]'); if(!ckb.length) return (f['no']||'N'); return ckb.attr(ckb.is(":checked")?'value':'offval'); };
$.fn.fmatter.estado=function(cv,opts,cObjt){ if(!$.vv(cv)||cv==='') return ''; var f=$.ocf(opts),full=$.vv(f['full'])?f['full']:false,em=f['empty'],i='No&nbsp;Definido'; var est='',def={A:'Activo',I:'Inactivo',E:'Eliminado',X:'No Visible'}; if($.vv(f['types'])){ est=f['types'][cv]; if($.isFunc(est)) est=est(cObjt); }else est=def[cv]; est=est||(em?'':i); return $('<div class="other-title vcenter">'+(full?est:cv)+'</div>').attr('title',est).attr('data-originaldata',cv).prop('outerHTML'); }; $.fn.fmatter.estado.unformat=$.unformatCellData;
$.fn.fmatter.title=function(cv,opts,cObjt){ var f=$.ocf(opts); if(!$.vv(cv)||cv===''||(!$.isFunc(f['title'])&&!$.isText(f['title']))) return ''; var s=$('<div class="other-title vcenter"></div>'); s.attr('title',$.funcOrVal(f['title'],cObjt,'',true)).html(cv); return s.prop('outerHTML'); }; $.fn.fmatter.title.unformat=$.unformatCellHtml;
$.fn.fmatter.gridButton=function(cv,opts,cObjt){ var o=$.cloneCO(opts,cObjt); var f=$.ocf(opts),a=f['action'],d=f['data'],dd=f['dataDefault']||{},cf=f['caseFalse']; if(!$.vv(a)) return '';  var con=$.getFunction(f['conditional']); var cfS=$.caseFalse(cf,o); if(cfS!=='') return cfS; if(!$.isFunc(con)||con(o)){ d=$.isArray(d)?$.newObj(d,o,dd):$.funcOrVal(d,o,o,$.isText(d)); return $.getGridButton(a,$.isObj(d)?$.extend(dd,d):d,f['title'],f['icon'],f['text'],f['type'],f['size'],f['attr'],f['icon2']); }return $.funcOrVal(cf,o,''); }; $.fn.fmatter.gridButton.unformat=$.unformatCellHtml;
$.fn.fmatter.tags=function(cv,opts,cObjt){var p=opts,f=$.ocf(p),o=cObjt,dk=f['data']||f['label']||'label',t=f['type']||"info",sp=f['sep']||",",d=$.isEmpty(cv)?[]:($.isArray(cv)?cv:cv.split(sp)),html='',title='',btn='',/*edit=false,*/act=f['action'],cus=f['button'],con=f['conditional'],r=f['remove']; $.each(d,function(i,vo){ var v=$.isObj(vo)?($.isFunc(dk)?dk(vo):($.isUnd(vo[dk])?'':vo[dk])):vo; v=(""+v).trim(); if(v!==''){ title+=((title===''?'':sp+" ")+v);html+=((html===''?'':'<span class="hidden">'+sp+' </span>')+'<span class="label label-'+t+'" title="'+v+'">'+v+(r?'&nbsp;&nbsp;<i class="'+$.createIcon('remove',true)+' dismiss" data-pos="'+i+'" title="Remover Item" onclick="'+($.isText(r)?r+'({pos:$(this).data(\'pos\'),'+p.colModel.name+':$.cloneData($(this).parent().parent().data(\'originaldata\')),rowId:'+p.rowId+'})':'$(\'#'+p.gid+'\').changeRowData('+p.rowId+',{'+p.colModel.name+':$.arraySplicePos($.cloneData($(this).parent().parent().data(\'originaldata\')),$(this).data(\'pos\'))});')+'"></i>':'')+'</span>'); } }); if(($.vv(act)||$.isFunc(cus))&&(!$.isFunc(con)||($.isFunc(con)&&!!con(o))))btn='<span class="pull-right">'+($.vv(cus)?cus(o,$.isText(cv)?d:cv):'')+' '+($.vv(act)?$.getGridButton(($.isFunc(act)?act.name:act)+"($.cloneData($(this).parent().parent().data('originaldata')),$.cloneData($(this).data('originaldata')))",/*{rowId:*/p.rowId/*,[p.colModel.name]:$.isText(cv)?d:cv*//*}*/,f['title']||'Editar Lista',f['icon']||'pencil',null,f['btnType']||'primary'):'')+'</span>'; return $('<div class="jqTags">'+btn+html+'</div>').attr('title',title).attr('data-originaldata',$.jsonParser($.isText(cv)?d:cv)).prop('outerHTML'); }; $.fn.fmatter.tags.unformat=$.unformatCellData;
$.fn.fmatter.union=function(cv,opts,cObjt){ if(opts.rowId==='') return cv; var f=$.ocf(opts),sp=f['sep']||" "; if($.isFunc(f['conditional'])) return f['conditional'](cObjt); if(!$.isUnd(f['cols'])){ var vc=""; $.each(f['cols'], function(i,v){ vc+=((vc===""?'':sp)+(cObjt[v]||""));}); }return ($.vv(cv)&&cv.trim()!==''?cv+sp:'')+vc; };
$.fn.fmatter.function=function(cv,opts,cObjt){ var f=$.ocf(opts),t=f['formatter'],d=$.getFunction(f['data']),v=opts.rowId===''?cv:0;  if(!$.isUnd(d)) v=opts.rowId===''&&!$.isUnd(f['noGroupFormat'])?v:d(cObjt); return (!$.isUnd(t)?(t!=='fixed'?$.numFormat(v,t):$.toFixed(v,f['decimals'])):v); }; $.fn.fmatter.function.unformat=function(cv,opts){ var f=$.ocf(opts),t=f['formatter']; return !$.isUnd(t)&&t!=='fixed'?$.numUnformat(cv,t):cv; };
$.fn.fmatter.json=function(cv,opts,cObjt){ var f=$.ocf(opts),n=f['name'],a=f['full'],s=$('<div></div>').attr('data-originaldata',$.jsonParser(a?cObjt:($.vv(n)?cObjt[n]:cv||''))); return s.prop('outerHTML'); }; $.fn.fmatter.json.unformat=$.unformatCellData;
$.cloneCO=function(op,co){ if(!$.vv(op.idName)) return co; var o=$.cloneData(co); if(!$.vv(o[op.idName]))o[op.idName]=op.rowId; return o; };
$.fieldHeader=function(v,f,rc){ return v||(rc[f]||""); }; $.cellExcel=function(id,cv,cObj,cm,rd){ if($.isUnd(cm['excel'])) return ''; var ef=eval('excelFormats'); return 'style="'+ef[cm['excel']]+'"';};
$.fieldSummarys=function(v,f,rc){ return $.fieldSummary($.isObj(v)?v:{msg:'TOTALES'},f,rc); }; $.fieldSummary=function(v,f,rc){ return "<div class='txtRight'>"+($.isObj(v)&&$.vv(v['msg'])?v['msg']:'TOTAL')+":</div>"; };
$.jqRowspan=function(id,cv,obj,cm,dat){ var d='rowspanId'; return " rowspan_"+cm[d]+"='"+(($.vv(obj)&&$.vv(cm[d])&&$.vv(obj[cm[d]]))?obj[cm[d]]:'')+"' "; };
$.cellAjust=function(ext){ return 'style="white-space: normal;" '+(ext||''); };
$.createInputAddon=function(op,o){ var av=$.funcOrVal(op['value'],o,'',op['inside']), h=$('<span class="input-group-'+(op['div']||'addon')+' alert-'+op['type']+'"></div>'); h.append(av); if(op['div']==='btn'){ var btn=true; try{ btn=$(av).is('button'); }catch(e){ btn=false; } if(btn===false) return null; } return h; };
$.createOption=function(lbl,val,vo,sel,del,addData){ lbl=lbl||'label'; val=val||'value'; var o=$.cloneData(vo),a=addData,ins=$.isObj(o),l=ins&&!$.isUnd(o[lbl])?o[lbl]:lbl,v=ins&&!$.isUnd(o[val])?o[val]:val.trim(),opS=$('<option role="option">'+l+'</option>').attr('value',v); if($.vv(sel)&&(($.isBool(sel)&&!!sel)||(sel==v)))opS.attr('selected','selected'); if(ins && !!del){ delete o[val];delete o[lbl]; } if(a)$.extend(opS[0].dataset,$.isArray(a)?$.newObj(a,o):o); return opS.prop('outerHTML');};
$.createFmatter=function(cv,opts,cObjt,ftype){var u,f=$.ocf(opts),con=$.getFunction(f['conditional']),d=f['data'],h={},o=cObjt,pr=f['prepend'],ap=f['append'],fval=$.funcOrVal(d,o,($.vv(cv)?cv:''),$.isText(d)),iI=ftype==='input',ft=f['type']; if($.isFunc(con)&&!con(o))return fval; if(iI&&$.vv(f['type'])){ if(['numeric','decimal'].indexOf(ft)>=0)$.extend(h,{style:"text-align:right",onkeypress:$.onEv(0),onkeyup:$.onEv(1,!1),onpaste:$.onEv(2,!1),negative:f['negative'],decimals:f['decimals']||(ft==='decimal'?'':u),placeholder:$.vv(f['decimals'])?'0.00':0}); } var id=opts.rowId,c=opts.colModel,n=f['name'],i=$.getFunction(f['dataInit']),pi=f['afterInit'],op=f['options'],lbl=f['label']/*||'label'*/,opval=f['value']/*||'value'*/,opS='',el=$('<'+ftype+' />').attr($.extend(h,{type:iI?"text":null,'id':id+"_"+c.name,rowid:id,name:$.vv(n)?(n===true?c.name:n):u,role:iI?'textbox':ftype,class:'editable inline-edit-cell nospin '+(f['classes']||'')+' '+$.jgrid.styleUI.jQueryUI.inlinedit.inputClass,/*'data-gid':opts.gid,*//*'data-pos':opts.pos,*//*'data-id-name':opts.idName,*//*'data-name':c.name,*//*'data-row-id':id,*/value:iI?fval:null},f['attr']||{}))/*.css('width','96%')*/; $.extend(el[0].dataset,{gid:opts.gid,rowId:id,name:c.name,pos:opts.pos}); if(!iI){try{ if($.isText(op))op=eval(op); opS=$.isFunc(op)?op(el,opts,cObjt):op; }catch(e){op=[];} if($.isArray(op))$.each(op,function(i,vo){ opS+=$.createOption(lbl,opval,vo,fval,!$.vv(lbl)&&!$.vv(opval),f['addData']); }); if(opS!==''){ el.append(opS); if($.isText(op)&&fval!=='') el.find('option[value='+fval+']').attr('selected','selected');} } if($.vv(pi))el.attr('afterinit','S'); if($.isFunc(i))i(el[0],opts,o); el.setCellEv(f['dataEvents']); var di=$('<div class="other-title'+($.vv(pr)||$.vv(ap)?' input-group input-group-xs textboxExa':'')+'"></div>'); if($.vv(pr)) di.append($.createInputAddon(pr,o)); di.append(el); if($.vv(ap)) di.append($.createInputAddon(ap,o)); return di.prop('outerHTML');};
$.fn.fillSelect=function(array,lbl,val,empty,addData){ if(!$.vv(this)||this.length===0) return; this.each(function(){ var t=$(this),c=t.hasClass('isChosen'),u,ar=array||[],a=addData,html=!empty?$.createOption(c?'':'Seleccione...',' '):'',iO=$.isObj(ar); $.each(ar,function(k,o){ html+=(iO?$.createOption(o,k):$.createOption(lbl,val,o,u,u,a)); });  t.html(html); if(c)t.trigger('chosen:updated'); if(t.hasClass('datatrigger')||t.data('trigger')) t.trigger('change'); }); return this; };
$.fn.fillSelectAdd=function(lbl,val,obj,sel,addData){ var u,t=this; if(!$.vv(t)||t.length===0) return; this.append($.createOption(lbl,val,obj,u,u,addData)); if(sel){ t.val(obj[val]); if(t.hasClass('datatrigger')||t.data('trigger')) t.trigger('change'); } if(t.hasClass('isChosen')) t.trigger('chosen:updated'); return t;  };
// FUNCIONES GENERALES JQUERY
$.fn.getDataForm=function(tipo,all){ if(!this.length) return {}; if(this[0].tagName.toUpperCase()!=='FORM') return this.getDataForced(tipo,all); if($.isBool(tipo)) all=tipo; all=($.isBool(all)?all:true); var data=this.serializeObject(); var aux={},del=[]; this.find('input[type=checkbox]:not(:checked),input:disabled,textarea:disabled,select:disabled,span.databind').each(function(){ var t=$(this), n=t.attr('name'), p=t.attr('type'); if(t.prop('tagName')==='SPAN'){ if(!$.isUnd(n)&&$.isUnd(data[n])) data[n]=(t.hasClass('isMoney')||t.hasClass('isNumber'))?''+$.numUnformat(t.text().trim(),t.hasClass('isNumber')?'number':null):t.text().trim(); }else if(!$.isUnd(n)&&$.isUnd(data[n])){ if($.isUnd(aux[n])){ if(!$.isUnd(p)&&p.toUpperCase()==='CHECKBOX'){ if(t.is(':checked')){ if(all) aux[n]=this.value; }else{ if(!$.isUnd(t.attr('offval'))){ aux[this.name]=t.attr('offval'); }else { if(all) aux[n]=''; } } }else{ if(all) aux[n]=t.val(); } } }else{ del.push(this.name); } } ); $.each(del,function(i,v){ delete aux[v]; }); $.extend(true,data,aux); this.find('select option:disabled:selected').each(function(){ var sNa=$(this).parent().attr('name'); if($.vv(sNa)&&($.isUnd(data[sNa])||data[sNa]===null)) data[sNa]=this.value;  }); this.find('input.isMoney,input.isNumber').each(function(){ var t=$(this); var sNa=t.attr('name'); if(!$.isUnd(sNa)) data[sNa]=$.numUnformat(t.val().trim(),t.hasClass('isNumber')?'number':null); }); this.find('select.getData').each(function(){ var sNa=$(this).attr('name'); if($.vv(sNa)&&$.vv(data[sNa])){ var tos=$(this).find('option:selected'), obD=$.extend({[sNa+'_Txt']:tos.text()},tos.data()); if($(this).hasClass('ins')) $.extend(data,obD); else data[sNa+'_Data']=obD; } }); if($.isText(tipo)) data[tipo]=true; return data; };
$.fn.getDataForced=function(tipo,all){ if(!this.length) return {}; if(this[0].tagName.toUpperCase()==='FORM') return this.getDataForm(tipo,all); var f=$('<form>'); f.append(this.clone(true)); var fo=f.find('form'); if(fo.length>0) fo.each(function(){ $(this).replaceWith($("<div/>").append($(this).children())); }); var d=f.getDataForm(tipo,all); f.empty().remove(); return d; };
$.fn.getData=function(tipo,all){ if(!this.length) return {}; var data={}; this.each(function(){ $.extend(data,$(this).getDataForm(tipo,all)); }); return data; };
$.fn.setData=function(data,reset,meta){ if(!$.vv(data)) data={}; if(!$.isObj(data)) return this; var chFs=[],kuFs=[],fields=this.find(":input,span.form-control,span.input-group-addon,p.form-control-static,span.databind");  if($.isText(reset)){meta=reset;}else{meta=($.vv(meta)?meta:'');} reset=($.isBool(reset)?reset:true);
    $.each(fields,function(){ var $this=$(this),name=(meta===''?$this.attr('name'):$this.data(meta)),nx=this.nextElementSibling,def=$this.data('default')||$this.attr('default'),tv=$this.val(),type=$this.attr('type'),trigger=($.vv($this.data('trigger'))||$this.hasClass("datatrigger")),keyup=($.vv($this.data('keyup'))||$this.hasClass("datakeyup"));
        if($.vv(name))
            if(type!=='radio'&&type!=='checkbox'){ if($this.is('select')&&$.vv(data[name+'_html'])) $this.html(data[name+'_html']); if($.vv(data[name])){ if($this.is(':input')){ var aux=tv,vd=data[name]===''?def||'':data[name]; if($this.is('select')&&vd===''){ var df=$this.find('option[default]'); if(df.length===1) vd=df.val(); $this.val(vd); }else $this.val($this.hasClass('isFixed')?$.toFixed(vd):($this.hasClass('isMoney')||$this.hasClass('isNumber')?$.numFormat(vd,$this.hasClass('isNumber')?'number':null):vd)); if($this.hasClass('isChosen')) $this.trigger("chosen:updated"); if($this.is('input[type=text]')&&keyup) kuFs.push($this); if(trigger&&aux!==data[name]) chFs.push($this); if($this.hasClass('clearable')) $this[data[name]!==''?'addClass':'removeClass']('x'); }else $this.html($this.hasClass('isFixed')?$.toFixed(data[name]):/*$.isNum(data[name])&&*/($this.hasClass('isMoney')||$this.hasClass('isNumber')?$.numFormat(data[name],$this.hasClass('isNumber')?'number':null):data[name])); if($this.hasClass("datatitle")) $this.attr('title',data[name].trim()); }else{ if(reset){ if($this.hasClass("datatitle")) $this.removeAttr('title'); if($this.is(':input')){ var aux=tv,vd=def||''; if($this.is('select')&&vd===''){ var df=$this.find('option[default]'); if(df.length===1) vd=df.val(); $this.val(vd); }else $this.val(vd); if($this.hasClass('isChosen')) $this.trigger("chosen:updated"); if($this.is('input[type=text]')&&keyup) kuFs.push($this); if(trigger&&aux!=='') chFs.push($this); if($this.hasClass('clearable')) $this.removeClass('x'); }else $this.html('');} } }
            else{ var aux=$this.prop("checked"); if($.vv(data[name])&&data[name].length){
                if(type==='radio') $this.prop("checked",tv===data[name]); if(type==='checkbox'){ if($.isArray(data[name])){ $this.prop("checked",false); $.each(data[name],function(i,v){ if(tv===v){$this.prop("checked",true);return !1;} }); }else $this.prop("checked",tv===data[name]); }
            }else{ if(reset) $this.prop("checked",def?($.isBool(def)&&def)||tv===def:!1); } if(trigger&&aux!==$this.prop("checked")) chFs.push($this); if(nx!==null&&$(nx).hasClass('ui-button'))$(nx)[$this.prop("checked")?'addClass':'removeClass']('ui-state-active');  }
    }); $.each(chFs,function(i,v){ v.trigger('change'); }); $.each(kuFs,function(i,v){ v.trigger('keyup'); }); return this;
};
$.getUrlSaveJson=function(str){ str=str||''; return ($.vv(UrlSaveJson)?UrlSaveJson:'/')+str; };
$.getDataJson=function(url,data,success,error,fail,allways,method){ var s=function(r){ var a; if($.vv(success)) a=success(r); return $.vv(a)?a:false; }; $.saveDataJson(url,data,s,error,fail,allways,method||'get'); };
$.postDataJson=function(url,data,success,error,fail,allways,method){ var s=function(r){ var a; if($.vv(success)) a=success(r); return $.vv(a)?a:false; }; $.saveDataJson(url,data,s,error,fail,allways,method||'post'); };
$.saveDataJson=function(url,data,success,error,fail,allways,method){ var jsonCall=(method==='GET'||method==='get'?$.get:$.post),msg,grid=($.isObj(url)?url:null),l=!$.vv(grid);  if(l) $('#loader').show(); else grid.jqGrid("progressBar",{method:"show",loadtype:'enable',htmlcontent:'Cargando...'}); var msg; url=(grid===null?(url||$.getUrlSaveJson()):grid[0].p.url);
	jsonCall(url,data, function(response){
		if(response['message']===''||!$.vv(response['message'])) if($.toBool(response['success'])===true) response['message']='La acci&oacute;n se ha realizado con &Eacute;xito!'; else response['message']='No se ha podido realizar la acci&oacute;n!';
		if($.toBool(response['success'])===true){ if($.vv(success)) msg=success(response); }else{ if($.vv(error)) msg=error(response); } if(msg!==false) $.alert(response['message'],null,($.toBool(response['success'])===true?'ok':'remove'));
	},'json').fail(function(e){ if(!$.vv(fail)) $.alert(); else{ msg=fail(e); if($.isText(msg)) $alert(msg); else if(msg!==false) $.alert();} }).always(function(){ if(l)$("#loader").fadeOut("slow"); else grid.jqGrid("progressBar",{method:"hide",loadtype:'enable'}); if($.vv(allways)) allways();});
};
$.fn.getFormData=function(ajax){var t=this,f=t.getData(ajax||t[0].id),fd=new FormData(t[0]);$.each(f,function(k,v){if(fd.get(k)===null){if($.isText(v)||$.isBool(v)){fd.append(k,v);}else if($.isArray(v)||$.isObj(v)){$.each(v,function(i,v1){fd.append(k+"["+($.isNum(i)?'':i)+"]",v1);}); } }});return fd;};$.getFormData=function(tipo,ajax){return $('#'+tipo.replace('#','')).getFormData(ajax);};
$.postMultiPartJson=function(url,data,success,error,fail,allways,method){ var s=function(r){ var a; if($.vv(success)) a=success(r); return $.vv(a)?a:false; }; $.saveMultiPartJson(url,data,s,error,fail,allways,method||'post'); };
$.saveMultiPartJson=function(url,data,success,error,fail,allways,method){ var jsonCall=(method==='GET'||method==='get'?'get':'post'),msg,grid=($.isObj(url)?url:null),l=!$.vv(grid);  if(l) $('#loader').show(); else grid.jqGrid("progressBar",{method:"show",loadtype:'enable',htmlcontent:'Cargando...'}); var msg; url=(grid===null?(url||$.getUrlSaveJson()):grid[0].p.url);
    $.ajax({ url:url, type:jsonCall, dataType:"json", data:data, cache:false, contentType:false, processData:false}).done(function(response){
        if(response['message']===''||!$.vv(response['message'])) if($.toBool(response['success'])===true) response['message']='La acci&oacute;n se ha realizado con &Eacute;xito!'; else response['message']='No se ha podido realizar la acci&oacute;n!';
        if($.toBool(response['success'])===true){ if($.vv(success)) msg=success(response); }else{ if($.vv(error)) msg=error(response); } if(msg!==false) $.alert(response['message'],null,($.toBool(response['success'])===true?'ok':'remove'));
    }).fail(function(e){ if(!$.vv(fail)) $.alert(); else{ msg=fail(e); if($.isText(msg)) $.alert(msg); else if(msg!==false) $.alert();} }).always(function(){ if(l)$("#loader").fadeOut("slow"); else grid.jqGrid("progressBar",{method:"hide",loadtype:'enable'}); if($.vv(allways)) allways();});
};
$.fn.getValidationJson=function(url,data,action,fail,allways){ var msg, $this=this, url=(url||$.getUrlSaveJson()); $this.fieldValid().addClass('fa fa-spin fa-spinner blue'); $.get(url,data, function(response){ if(response['success']==='') $this.fieldValid(); else $this.fieldValid(!$.toBool(response['success'])?response['state']||false:true, $.toBool(response['success'])?null:response['message']); if($.vv(action)) action(response);  },'json').fail(function(e){ if($.vv(fail)) msg=fail(e); $this.fieldValid(false,'Fallo la conexion.'); }).always(function(){ if($.vv(allways)) allways(); }); };
$.fn.fieldValid=function(state,message){ var next=this.next(),i=next.show().find('i'); if(!$.vv(next.data('title'))){ next.data('title',$.vv(next.attr('title'))?next.attr('title'):''); next.data('class',i.attr('class')); } next.removeClass('alert-danger alert-warning'); i.removeAttr('class'); if(state==='return'){ next.attr('title',next.data('title')); return i.addClass(next.data('class')); } if(state==='hide'){ next.hide(); state=''; }  i.addClass((!$.isBool(state)?(state==='warning'?$.createIcon('warning-sign orange',true):''):(state?$.createIcon('ok green',true):$.createIcon('remove red',true)))); next.removeAttr('title'); if($.isText(message)) next.attr('title',message); if(state==='warning')next.addClass('alert-warning'); if(state===false)next.addClass('alert-danger');  return i; };
$.fn.Search=function(form,tipo){ this.setGridParam({postData:null}); var a=$.isObj(form),jform=a?form:$(form),e=this.getGridParam('postExtra')||{}; if(a){ if($.vv(tipo))jform[tipo]=true; }else jform.effect("highlight",{},500);  this.jqGrid('setGridParam',{datatype:'json',postData:$.extend(true,e,a?jform:jform.getData(tipo))}).gridUpdate(1); };
$.fn.SearchOrDialog=function(form,tipo,dialog,callback){
	var postdata=$(form).getData(tipo),jgrid=this;postdata['page']=1;postdata['rows']=2; $(form).effect("highlight",{},500);
	$.get(this[0].p.url,postdata, function(response){ if(parseInt(response['records'])===1){callback(response['rows'][0]);}else{jgrid.Search(form,tipo);$(dialog).dialog("open");} },'json');
};
$.fn.SearchOrDialogArray=function(array,tipo,dialog,callback){
	var postdata=array,jgrid=this;postdata['page']=1;postdata['rows']=2;postdata[tipo]=true; /*$(form).effect("highlight",{},500);*/
	$.get(this[0].p.url,postdata, function(response){ if(parseInt(response['records'])===1){callback(response['rows'][0]);}else{ jgrid.Search(postdata,tipo); $(dialog).dialog("open");} },'json');
};
$.fn.moveComp=function(comp){$('#loader').show();this.hide();$(comp).show();$('#loader').fadeOut('slow');return $(comp);};
$.fn.dateLimits=function(minDate,maxDate){ if($.vv(minDate))this.datepicker( "option","minDate",minDate ); if($.vv(maxDate))this.datepicker("option","maxDate",maxDate ); return this;};
$.fn.formSubmit=function(){ this.removeAttr('novalidate'); $('<input type=\'submit\' />').hide().appendTo(this).click().remove();return this;};
//$.fn.createChosen=function (clase,options){ /*Requiere jquery.chosen*/ clase=clase||'input-sm';options=$.extend({width:"100%"},(options||{})); this.each(function(i,obj){ var tab=$(obj).attr('tabindex')||''; /*if(tab!=='') $(obj).removeAttr('tabindex');*/ if(!$.vv(options['template'])) $(this).chosen(options); else $(this).chosenDesc(options); var id=$(obj).attr('id')||''; if(id!==''){$("#"+id+"_chosen").addClass('bs-chosen').find('.chosen-single').addClass('form-control '+clase);$("#"+id+"_chosen").find(".chosen-search").find('input').addClass('text');  if(tab!==''){ $("#"+id+"_chosen").attr('tabindex',tab).on('focus',function(){  $(obj).trigger('chosen:open.chosen'); });  } } }); return this; };
$.fn.tableRemoveColumn=function(columnIndex,remove){ if(!$.vv(columnIndex))return this; remove=$.vv(remove)?remove:true; var index=[];
	if($.isArray(columnIndex)){index=columnIndex;index.sort(function(a, b){return b-a;});}else{index=[columnIndex];}
	for(var i=0;i<index.length;i++){ if(remove){this.find("tbody").find("tr").find("td:eq("+index[i]+")").remove();this.find("thead").find("tr").find("th:eq("+index[i]+")").remove();}else{this.find("tbody").find("tr").find("td:eq("+index[i]+")").hide();this.find("thead").find("tr").find("th:eq("+index[i]+")").hide();}  }return this;
};
$.fn.tableRemoveRow=function(rowIndex,remove){ if(!$.vv(rowIndex))return this; remove=$.vv(remove)?remove:true; var index=[]; if($.isArray(rowIndex)){index=rowIndex;index.sort(function(a, b){return b-a;});}else{index=[rowIndex];}	for(var i=0;i<index.length;i++){if(remove){this.find("tbody").find("tr:eq("+index[i]+")").remove();}else{this.find("tbody").find("tr:eq("+index[i]+")").hide();} }return this; };
//$.imprimirUrl=function(url,css){ $('#loader').show(); $.get(url, {}, function(r){ var p1=/<body[^>]*>((.|[\n\r])*)<\/body>/im, p2=/<head[^>]*>((.|[\n\r])*)<\/head>/im, p3=/<style[^>]*>((.|[\n\r])[^"]*)<\/style>/gmi, b=r, body=p1.exec(b), s='', styles; if($.vv(body)){ var head=p2.exec(b); b=body[1]; if($.vv(head)) styles=head[1].match(p3); if($.isArray(styles)) $.each(styles,function(i,v){ s=s+v; }); } $('<div>'+s+b+'</div>').printElement({ pageTitle:'Reporte Exa', overrideElementCSS:[{ href:(css||'../../mascaras/model1/estilos/print.css'), media:'print'}]}); }).fail(function (){ $.alert(); }).always(function(){ $("#loader").fadeOut("slow"); }); }; // requiere printElement.js
// Requiere jquery.maskmoney.js
/*$.MoneySet=function(id){$(id).maskMoney({prefix:'$ ',thousands:',',decimal:'.',precision:4,affixesStay:true,allowNegative:true,allowZero:true});$(id).maskMoney('mask');}; $.MoneyUnSet=function(id){$(id).maskMoney('destroy');}*/
$.objColEqual=function(obj,col,val){ if(!$.isObj(obj)) return false; if($.isBool(val)) return($.toBool(obj[col])===val); else if(isNaN(val)) return (String(obj[col])===String(val)); else if(isNaN(obj[col])) return (String(obj[col])===String(val));  else return (obj[col]*1===val*1); };
$.arraySplicePos=function(array,pos,can){ array.splice(pos,can||1); return array; };
$.arrayIsValidKey=function(array,columnName){ if((!$.isArray(array)|| !$.vv(columnName))||(array.length>0 && $.isUnd(array[0][columnName]))) return false; return true;};
$.arraySpliceWhere=function(array,columnName,value,all){ if($.isFunc(columnName)){ var where=columnName; all=($.isBool(value)?value:true); for(var i=array.length-1;i>=0;i--) if(where(array[i])){ array.splice(i,1); if(!all) break;} return array; } if($.isUnd(all))all=true; if(!$.arrayIsValidKey(array,columnName)||$.isUnd(value)) return array;  for(var i=array.length-1;i>=0;i--) if($.objColEqual(array[i],columnName,value)){array.splice(i,1); if(!all) break;} return array; };
$.arraySpliceFields=function(array,columns){ if(!$.isArray(array)||!$.vv(columns)) return array; if($.isText(columns)) columns=[columns]; for(var j=0;j<array.length;j++){ $.each(columns,function(i,v){ delete array[j][v]; }); } return array; };
$.arrayExistsVal=function(array,columnName,value){ if(!$.arrayIsValidKey(array,columnName)||$.isUnd(value)) return false; for(var i=0;i<array.length;i++) if($.objColEqual(array[i],columnName,value)){return true;} return false; };
$.arrayCountVal=function(array,columnName,value){ if(!$.isFunc(columnName)) if(!$.arrayIsValidKey(array,columnName)||$.isUnd(value)) return 0; var cont=0; for(var i=0;i<array.length;i++) if($.isFunc(columnName)){ if(columnName(array[i])) cont++; }else if($.objColEqual(array[i],columnName,value)) cont++; return cont; };
$.arrayMaxVal=function(array,columnName,columnName2,value){ if(!$.arrayIsValidKey(array,columnName)) return; if((!$.isUnd(columnName2)&&!$.arrayIsValidKey(array,columnName2))||!$.isUnd(columnName2)&&$.isUnd(value)) return; var max=null,wh=(!$.isUnd(value)); for(var i=0;i<array.length;i++) if(wh){ if($.objColEqual(array[i],columnName2,value)&&!isNaN(array[i][columnName])) max=(max===null||(array[i][columnName]*1)>max?(array[i][columnName]*1):max); }else{ if(!isNaN(array[i][columnName])) max=(max===null||(array[i][columnName]*1)>max?(array[i][columnName]*1):max); } return max; };
$.arrayMinVal=function(array,columnName,columnName2,value){ if(!$.arrayIsValidKey(array,columnName)) return; if((!$.isUnd(columnName2)&&!$.arrayIsValidKey(array,columnName2))||!$.isUnd(columnName2)&&$.isUnd(value)) return; var min=null,wh=(!$.isUnd(value)); for(var i=0;i<array.length;i++) if(wh){ if($.objColEqual(array[i],columnName2,value)&&!isNaN(array[i][columnName])) min=(min===null||(array[i][columnName]*1)<min?(array[i][columnName]*1):min); }else{ if(!isNaN(array[i][columnName])) min=(min===null||(array[i][columnName]*1)<min?(array[i][columnName]*1):min); } return min; };
$.arraySumVal=function(array,columnName,columnName2,value){ if(!$.arrayIsValidKey(array,columnName)) return; if((!$.isUnd(columnName2)&&!$.arrayIsValidKey(array,columnName2))||!$.isUnd(columnName2)&&$.isUnd(value)) return; var sum=0,a=array,wh=(!$.isUnd(value)); for(var i=0;i<a.length;i++) if(!isNaN(a[i][columnName])) if(wh){ if($.objColEqual(a[i],columnName2,value)) sum+=(a[i][columnName]*1); }else{ sum+=(a[i][columnName]*1); } return sum; };
$.arrayGetWhere=function(array,where,index){  var iaux=($.isText(index)?true:($.isBool(index)?index:false)); var resp=new Array(); if(!$.isFunc(where)) return resp; if(!$.isArray(array)) return resp; if(iaux) index=($.isText(index)?index:'index');  for(var i=0;i<array.length;i++) if(where(array[i])){ if(iaux) array[i][index]=i; resp.push(array[i]);} return resp; };
$.arrayGetItems=function(array,columnName,value,index){  if(!$.arrayIsValidKey(array,columnName)||$.isUnd(value)) return new Array(); return $.arrayGetWhere(array,function(d){ return $.objColEqual(d,columnName,value); },($.isText(index)||$.isBool(index)?index:true)); };
$.arrayGetItem=function(array,columnName,value,index){ var items=$.arrayGetItems(array,columnName,value,index); if(items.length===1) return items[0]; else return null; };
$.arrayGetColumns=function(array,columns){
    var resp=new Array(); if(!$.isArray(array)) return resp; if($.isArray(columns)){for(var i=(columns.length-1);i>=0;i--){ if(!$.arrayIsValidKey(array,columns[i])) columns.splice(i,1); }}else{ if(!$.arrayIsValidKey(array,columns))return resp;} if(!columns.length) return resp;
	for(var j=0;j<array.length;j++){ var item={}; if($.isArray(columns)) $.each(columns,function(i,v){ item[v]=$.cloneData(array[j][v]); }); else item[columns]=$.cloneData(array[j][columns]); resp.push(item); } return resp;
};
$.createDatePickers= function(id){ if(!$.vv(id)) return; return $(id).createDatePickers(); };
$.fn.createDatePickers= function(opts){ opts=($.isObj(opts)?opts:{}); this.datepicker($.extend({changeMonth: true,changeYear: true, dateFormat: 'yy-mm-dd',firstDay: 1, hideMsg:true},opts)); if(opts['clean']!==true) this.datepicker("setDate", new Date()); if(opts['checkAvailability']===true) this.on('change',function(){ var $t=$(this),d=$t.val(), set=$t.data('datepicker').settings, min=set['minDate'], max=set['maxDate'], errmsg=''; $t.fieldValid(set['hideMsg']?'hide':'return'); if(d.length===10){ if(!$.dateValid(d)) errmsg='Ingrese una fecha v\u00E1lida!'; else{ if($.vv(min)&&min>d) errmsg='Esta Fecha no puede ser menor a '+min+'!';  if($.vv(max)&&max<d) errmsg='Esta Fecha no puede ser mayor a '+max+'!';  } if(errmsg!==''){ $t.val('').fieldValid('warning',errmsg); setTimeout(function(){ $t.focus(); },0);  } } }); return this; };
$.createDateRange=function(from,to,sep){ var f=from,t=to; if(!$.vv(f)||!$.vv(t)||($.isObj(f)&&!f.length)||($.isObj(t)&&!t.length)) return; var today=new Date(); f=$(f);t=$(t); f.createDatePickers({onClose:function(sd){ t.datepicker("option","minDate",sd); } }).datepicker("setDate", new Date(today.getTime() - ( ($.isNum(sep)?sep:30) * 24 * 3600 * 1000))); t.createDatePickers({onClose:function(sd){ f.datepicker("option","maxDate",sd ); } }).datepicker("setDate", today);f.data('default',f.val());t.data('default',t.val());/*f.add(f).datepicker( "option", "showAnim", "blind" );*/};
$.fn.createDateRange=function(sep){ var t1=this; t1.each(function(){ var t2=$(this); $.createDateRange(t2.find('input[name=Fec_Ini],input[ini]'),t2.find('input[name=Fec_Fin],input[fin]'),sep); }); return t1; };
$.createIcon=function(str,justClass,attr,css,tag){ if(!$.vv(str)||str==='') return ''; tag=tag||'i'; var c=(!str.indexOf("ui-icon-")?'':(!str.indexOf("glyphicon")?'glyphicon ':(!str.indexOf("fa-")||!str.indexOf("fa fa-")?'fa ':'glyphicon glyphicon-')))+str; if(justClass===true) return c; var $t=$('<'+tag+($.isText(attr)?' '+attr:'')+($.isText(css)?' style="'+css+'"':'')+' class="'+c+'"/>'); if($.isObj(css)) $t.css(attr); return $t.prop('outerHTML'); };
$.widget("ui.dialog",$.ui.dialog,{ option:function(opt,val){ if($.isObj(opt)&& $.isText(opt['icon'])) this.element.prev('.ui-dialog-titlebar').find('i').attr('class','').addClass($.createIcon(opt['icon'],true)); if(opt==='icon'&& $.isText(val)) this.element.prev('.ui-dialog-titlebar').find('i').attr('class','').addClass($.createIcon(val,true)); return this._super(opt,val); }  });
$.createDialog=function(comp,height,width,noTitleStuff,action,icon){ return $(comp).createDialog({height:(height||300),width:(width||400),noTitleStuff:noTitleStuff,icon:icon},action); };
$.fn.createDialog=function(options,action){ var $t=(!this.length)?$('<div id="'+this.selector.replace("#","")+'" style="display:none"><div>').appendTo('body'):this;  options=($.isObj(options)?options:{});
    var icon=options['icon'],noTitleStuff=($.vv(options['noTitleStuff'])?options['noTitleStuff']:true ),dClass=(noTitleStuff?"TitleStuff":"noTitleStuff"); ($.vv(options['dialogClass'])?options['dialogClass']+=' '+dClass:options['dialogClass']=dClass);
    var opts={
        height: 300, width: 400, closeText:"Cerrar Ventana", position:{my: "center",at: "center",of: $('body')},
        show: {effect: "fade",duration: 500},hide: {effect: "fade",duration: 200},modal:true,autoOpen:false,resizable:false,
        close: function(){var dg=$(this),ac=options['afterClose']; $(dg.parent()[0].nextSibling).unbind('click');if($.isFunc(action))action.call(dg);if($.isFunc(ac))ac.call(dg); },
        open: function(){var dg=$(this),ao=options['afterOpen']; $('.ui-widget-overlay').bind('click', function(){ dg.dialog('close'); });if($.isFunc(ao))ao.call(dg);}
    };  $.extend(opts,options); $t.each(function(){ $(this).dialog(opts).parent().children(".ui-dialog-titlebar").prepend($.createIcon($.vv(icon)?icon:'paperclip')); });
    if(options['noBorder']===true) $t.addClass('ui-dialog-noborder'); if(options['noOverflow']===true) $t.addClass('ui-dialog-nooverflow'); if($.vv(options['extraClass'])) $t.addClass(options['extraClass']); return $t;
};
$.createDialogConfirm=function(message,data,accion,cancel){
	message=message||'Esta seguro que desea realizar esta <b>acci&oacute;n</b>.'; var dialog=$('<div title="CONFIRMAR ACCI&Oacute;N">'+'<div style="font-size:14px;"><center>'+message+'</center></div></div>');//$("body").append(dialog);
	dialog.dialog({
	  dialogClass: 'dialog-confirm-test',closeText:"Cerrar y Cancelar",modal:true,autoOpen:true,resizable:false, position:{my: "center",at: "center",of: $('body')},
          buttons:[{text:"Aceptar", click:function(){$(this).dialog( "close" );if(data!==null){accion(data);}else{accion();}}, icons:{ primary: "ui-icon-check" }},{text: "Cancelar", click:function(){$(this).dialog( "close" );if($.vv(cancel))cancel();}, icons: { primary: "ui-icon-closethick" }}],
	  close: function(){$($(this).parent()[0].nextSibling).unbind('click'); $(this).remove();},
	  open: function(){ var dg=$(this); $(dg.parent()[0].nextSibling).bind('click', function (){ dg.dialog('close'); if($.vv(cancel))cancel(); });}
    }).parent().children(".ui-dialog-titlebar").prepend($.createIcon('question-sign'));
};
/*$.fn.createWYSIWYG= function(opts){ // Requiere summernote.js
	var o=$.extend({lang:'es-ES',height:100,placeholder:'Ingrese Texto..',toolbar:[['style',['bold','italic','underline','clear']],['fontsize',['fontsize']],['color',['color']],['para',['ul', 'ol','paragraph']]],popover:{image:[],link:[],air:[]},disableResizeEditor:true},($.isObj(opts)?opts:{}));
	this.each(function(){ $(this).summernote(o);$(this.nextSibling).find('.note-toolbar').find('.btn.btn-default').removeClass('btn-sm').addClass('btn-xs');$(this.nextSibling).find('.note-statusbar').hide(); }); return this;
};*/
$.fn.initDivs=function(init){ var a=this,i=init||{}; if(!a.length)$.each(i,function(k){ a=a.add($('#'+k)); }); a.hide().each(function(){ var d=$(this),dk=d.attr('id'); if($.isFunc(i[dk])){ d.css({display:'block',visibility:'hidden'}); i[dk](); d.css('visibility','').hide(); } }); return this; }; $.initDivs=function(i){ return $().initDivs(i); };
$.fn.createTabs=function(options,loader,grids){ var op=options||{},i=op['init']; if($.isObj(i)){ this.find('>div.ui-tabs-panel').initDivs(i); delete(op['init']);} loader=($.vv(loader)?loader:true);grids=($.vv(grids)?grids:true);var ba=op['beforeActivate'],ac=op['activate'],opts={cache:false,beforeActivate:function(event,ui){ if(loader) $("#loader").show(); if($.isFunc(ba))ba.call(this,event,ui);  },activate:function(event,ui){ if(grids) ui.newPanel.updateGridsSizes(); if(loader) $("#loader").fadeOut("slow"); if($.isFunc(ac))ac.call(this,event,ui); }};if($.isObj(op)) delete(op['beforeActivate']);delete(op['activate']); $.extend(true,opts,op); this.tabs(opts); return this; };
$.fn.createFormSearch=function(form){ if(!$.vv(form)) form={}; if(!$.isObj(form)||!this.length) return this; var $this, name=this.attr('id'),id=name.replace("Form",""),label=($.vv(form['label'])?form['label']:'B&uacute;squeda'),txtF=($.vv(form['text'])?form['text']:'search'),optR=($.vv(form['radio'])?form['radio']:'op_opciones'),title=($.vv(form['title'])?form['title']:'Persona'),opts=(($.vv(form['options']) && $.isArray(form['options']))?form['options']:[{label:'&nbsp;&nbsp;Apellido/Nombre&nbsp;&nbsp;',value:'d'},{label:'&nbsp;&nbsp;C&eacute;dula/R.U.C&nbsp;&nbsp;',value:'c'}]),optts='';
	$.each(opts,function(i,v){ optts=optts+'<input id="'+id+'Rdio'+i+'" name="'+optR+'" type="radio" value="'+v['value']+'" '+(i===0?'checked=""':'')+' onclick="setfocus(this.form.'+txtF+')" alt="" /><label for="'+id+'Rdio'+i+'">'+v['label']+'</label>'; });
	if(!this.find('fieldset').length) this.append('<fieldset class="exa-fieldset"><legend class="Titulos2">Filtros</legend></fieldset>'); $this=$((this.find('fieldset'))[this.find('fieldset').length-1]);
	$this.append((optts.length>0?'<div class="form-group form-group-options"><label class="col-xs-2 control-label label-xs">Filtrar Por:</label><div class="col-xs-6 radioset">'+optts+'</div></div>':'')+
		'<div class="form-group form-group-search"><label class="col-xs-2 control-label">'+label+':</label><div class="col-xs-7"><div class="input-group"><input name="'+txtF+'" onkeydown="if(event.keyCode===13) this.form.submit()" type="text" size="50" maxlength="50" placeholder="Ingrese '+label+'..." autofocus  class="form-control input-sm clearable submit"/><span class="input-group-btn form-group-search-btn"><button type="button" onclick="this.form.submit()" class="btn btn-success btn-sm" title="Buscar '+title+'" tabindex="-1" >'+$.createIcon('search')+'</span> <span>Buscar</span></button></span></div></div></div>'+
		'<input type="text" style="display:none" tabindex="-1" />'); return this.addClass('form-horizontal normal');
};
$.fn.createFormSearchPrecio=function(form){ if(!$.vv(form)) form={}; if(!$.isObj(form)||!this.length) return this; var $this, name=this.attr('id'),id=name.replace("Form",""),label=($.vv(form['label'])?form['label']:'B&uacute;squeda'),txtF=($.vv(form['text'])?form['text']:'search'),optR=($.vv(form['radio'])?form['radio']:'op_opciones'),title=($.vv(form['title'])?form['title']:'Persona'),opts=(($.vv(form['options']) && $.isArray(form['options']))?form['options']:[{label:'&nbsp;&nbsp;Apellido/Nombre&nbsp;&nbsp;',value:'d'},{label:'&nbsp;&nbsp;C&eacute;dula/R.U.C&nbsp;&nbsp;',value:'c'}]),optts='';
    $.each(opts,function(i,v){ 
        optts=optts+'<input id="'+id+'Rdio'+i+'" name="'+optR+'" type="radio" value="'+v['value']+'" '+(i===0?'checked=""':'')+' onclick="setfocus(this.form.'+txtF+')" alt="" /><label for="'+id+'Rdio'+i+'">'+v['label']+'</label>'; });
    if(!this.find('fieldset').length) this.append('<fieldset class="exa-fieldset"><legend class="Titulos2">Filtros</legend></fieldset>'); $this=$((this.find('fieldset'))[this.find('fieldset').length-1]);
    $this.append((optts.length>0?'<div class="form-group form-group-options"><label class="col-xs-2 control-label label-xs">Filtrar :</label><div class="col-xs-6 radioset">'+optts+'</div></div>':'')+
        ' <input id="Tpv_Cod2" name="Tpv_Cod2" type="hidden" value=""> <div class="form-group form-group-search"><label class="col-xs-2 control-label">'+label+':</label><div class="col-xs-7"><div class="input-group"><input name="'+txtF+'" onkeydown="if(event.keyCode===13) this.form.submit()" type="text" size="50" maxlength="50" placeholder="Ingrese '+label+'..." autofocus  class="form-control input-sm clearable submit"/><span class="input-group-btn form-group-search-btn"><button type="button" onclick="this.form.submit()" class="btn btn-success btn-sm" title="Buscar '+title+'" tabindex="-1" >'+$.createIcon('search')+'</span> <span>Buscar</span></button></span></div></div></div>'+
        '<input type="text" style="display:none" tabindex="-1" />'); return this.addClass('form-horizontal normal');
};
$.createOrderGrid=function(options,mirror,id){ var html='',u; $.each(options,function(i,v){ html+=$.createOption(u,u,v,v['def']); if(v['def']&&$.vv(mirror)) $(mirror).val(v['value']); }); return ' <div class="pull-right"><b>ORDENAR POR:</b>&nbsp;<select class="orderSelect"'+($.vv(id)?' id="'+id+'"':'')+($.vv(mirror)?' onchange="$(\''+mirror+'\').val(this.value)"':'')+'><option value="">No ordenar</option>'+html+'</select>'; };
$.fn.createGrid=function(options,local,pager,pgoptions){
    var u=undefined,t=this, og=options||{}; if($.isNum(og.height)) t.parent().css('min-height',((og.height*1)+(pager?30:15)+(og.footerrow?20:0)+(og.caption?24:0)+(og.leyenda?13:0))+'px'); local=($.vv(local)?local:false);if($.vv(pager)) pager='#'+pager.replace("#",""); var select=($.isBool(og.selectGridRows)?og.selectGridRows:true), pglocal=(local?{pgbuttons:false,pgtext:null}:{}),width=t.parent().actual('width');
    var opts={mtype:"GET",datatype:(local?'local':'json'),postExtra:{},regional:'es',autowidth:false,width:width,shrinkToFit:true,hidegrid:false,responsive:true,cmTemplate:{sortable:false},gridview:true,rownumbers:true,viewrecords:true,altRows:true,altclass:"myAltRowClass",rowNum:(local?10000000:250),height:(local?150:200),pager:($.vv(pager)?pager:''),tabIndex:'-1', bindKeys:!select?false:true,onSelectRow:!select?function(id){$(t).resetSelection();$(t).find('tr#'+id).attr('tabindex','-1');}:null,subGridOptions:{plusicon:"ui-icon-triangle-1-e",minusicon:"ui-icon-triangle-1-s",openicon:"ui-icon-arrowreturn-1-e",reloadOnExpand:false,selectOnExpand:true}/*,ajaxRowOptions: { async: true },*/}; $.extend(opts,pglocal); if($.isObj(og))$.extend(opts,og);
    var leA=opts['leyenda'],totCl=opts['totalCols'],totD=opts['totalDefault'], stC=opts['stateCol'],stCnf=opts['stateConfig']||{I:'cellRed2'},stCnd=opts['stateCondition'];
    if(!$.isUnd(totCl)&&opts['footerrow']){ t.on('jqGridAfterLoadComplete',function(){ if(opts['totalPage']&&opts['userDataOnFooter']){ var dF=t[0].grid.sDiv, nF=$(dF).find("tr.myfootrow").remove(), oF=$(dF).find("tr.footrow:not(.myfootrow)"); nF=oF.clone(); nF.addClass("myfootrow").children("td").each(function(){ this.style.width=""; }).end().insertAfter(oF); oF.find('td').html(''); } t.setGridSummary(totCl,totD,opts['totalNoFormat'],opts['totalFormatFunc']); }); } $.each(opts['colModel'],function(i,v){ if(!$.isUnd(v.excel)){ v.cellattr=$.cellExcel; } if(['gridButton','textboxExa','selectExa','checkboxExa','estado','truefalse','title','tags'].indexOf(v['formatter'])>=0) v['title']=false; switch(v['formatter']){ case 'tags':v['cellattr']=$.cellAjust;break; case 'gridButton':$.extend(v,{viewable:false,align:'center'});break; case 'function':if(['currency','number'].indexOf((v['formatoptions']||{})['formatter'])>=0)v['align']=v['align']||'right';break; case 'number':case 'currency':v['align']=v['align']||'right';break; }
    if($.isText(v['rowspanId'])){ t.on('jqGridAfterLoadComplete',function(){ var rs='rowspan_'+v['rowspanId']; var l={}; t.find('>tbody>tr>td['+rs+']').filter(function(){ var id=$(this).attr(rs); if(l[id]) return false; else { l[id]=true; return true; }  }); t.find('>tbody>tr>td['+rs+']').css('display','none'); var it=t.find('>tbody>tr>td['+rs+'],>tbody>tr.jqgroup>td'); $.each(l,function(k,v){ var fi; it.each(function(i){ var t1=$(this); if(t1.attr(rs)===k){ var aux1=i-1,aux2=i+1; if(aux1===-1 || $(it[aux1]).attr(rs)!==k) fi=t1.attr('rowspan','1').css('display','').addClass('myAltRowClass'); else{ if(!$.isUnd(fi)&&$(it[aux1]).attr(rs)===k) fi.attr('rowspan',fi.attr('rowspan')*1+1); } if(aux2>=it.length || $(it[aux2]).attr(rs)!==k) fi=undefined; } }); }); }); } });
    if((!$.isUnd(stC)||$.isFunc(stCnd))&&!$.isUnd(stCnf)){ t.on('jqGridAfterLoadComplete',function(ev,glc){ var r=($.isUnd(glc)||$.isUnd(glc['rows']))?t.getGridBatch():glc.rows; var cs=[],fr=$('#'+t.attr('id')+'_frozen'),k=t.pk();; $.each(stCnf, function(i,c){ cs.push(c); }); t.add(fr).find('>tbody >tr'+(r.length===1?'#'+r[0][k]:'[role=row]:not(.ui-subgrid)')+' td').removeClass(cs.join(' ')); $.each(r,function(i,v){ var cTi=($.isFunc(stCnd)?stCnd(v):undefined)||v[stC]; if(!$.isUnd(cTi)&&!$.isUnd(stCnf[cTi])){ t.add(fr).find('tr#'+v[k]+' td:not(.jqgrid-rownum)').addClass(stCnf[cTi]); } }); }); } if(!$.isUnd(opts['orderOptions'])){ opts['caption']=opts['caption']||''; opts['caption']+=$.createOrderGrid(opts['orderOptions'],opts['orderMirror'],opts['orderId']); if($.isUnd(opts['orderMirror'])) opts['postExtra']['order']=function(){ var s=t.getCaption(true).find('select.orderSelect'); return s.length?s.val():u;  };  } t.on('jqGridAfterLoadComplete',function(ev,glc){ var it=t.find('>tbody >tr[role=row]:not(.ui-subgrid)').find('input[afterinit],select[afterinit]'); if(it.length===0) return; var r=($.isUnd(glc)||$.isUnd(glc['rows']))?t.getGridBatch():glc.rows; it.each(function(i,e){ var opt=$.cloneData($(e).removeAttr('afterinit').data()),o=$.cloneData($.arrayGetItem(r,t[0].p.keyName,opt.rowId,false)),c=t[0].p.colModel[opt.pos],ai=c.formatoptions['afterInit']; try{ if(!$.isFunc(ai)) ai=eval(ai); opt.colModel=c; ai.call(t,e,opt,o); }catch(e){} }); });
    t.jqGrid(opts); if(!$.isUnd(totCl)&&opts['clearFootRow']===true) t.clearFootRow(totCl); if(opts['bindKeys']) t.jqGrid('bindKeys'); if($.vv(pager)){ var pgopts={ edit: false, add: false, del: false, search: false, refresh: (local?false:true), view: true, position: "left", cloneToTop: false }; if($.isObj(pgoptions)) $.extend(pgopts,pgoptions); t.navGrid(pager,pgopts); }
    if($.isObj(totD)) t.jqGrid('footerData','set', totD,true); if(!$.isUnd(leA)){ var ley=$('<div class="Titulos2 footer-leyenda"></div>'),htL=''; $.each(leA,function(i,v){ htL+=((htL!==''?'&nbsp&nbsp|&nbsp&nbsp':'')+$.createIcon(v['icon'])+" "+v['label']); }); ley.html('<strong>Leyenda:&nbsp;&nbsp;&nbsp;</strong>'+htL).insertAfter("#gbox_"+t.attr('id')); } t.parent().css('min-height',''); if(local===false&&opts.datatype==='local') t[0].p.datatype='json';  return t;
};
$.closeDialogGrid=function(dialog){ return '<button type="button" role="button" tabindex="-1" class="ui-button ui-widget ui-state-default ui-corner-all pull-right" title="Cerrar Ventana" onclick="$(\'#'+dialog+'\').dialog(\'close\')"><span class="ui-button-icon-primary ui-icon ui-icon-closethick"></span></button>'; };
$.fn.createDialogDetail=function(grid,dialog){ dialog=dialog||{}; grid=$.extend({caption:'',colModel:[]},$.isArray(grid)?{colModel:grid}:grid||{}); var p=$.vv(grid['pager']),$t,di=this.selector.replace("#",""),id=di.replace("Dialog","");
    var g=$.extend(grid,{responsive:false,height:!isNaN(grid['height'])?grid['height']:219, width:!isNaN(grid['width'])?grid['width']:593,caption:($.createIcon(dialog['icon'])+"&nbsp;")+(dialog['title']||grid['caption']||this.attr('title')||'')+'&nbsp;'+$.closeDialogGrid(di)});
    $t=this.createDialog($.extend(dialog,{height:(grid['height']*1)+54+(grid['footerrow']===true?20:0)+(p?23:0),width:(grid['width']+1)+7,noTitleStuff:false,noBorder:true,noOverflow:true,extraClass:'noMargin'}));
    if(!$t.find('#'+id+'Grid').length) $t.append('<div class="condensed-header"><table id="'+id+'Grid"></table>'+(p?'<div id="'+g['pager'].replace("#","")+'"></div>':'')+'</div>'); $t.find('#'+id+'Grid').createGrid(g,true,$.vv(p)?g['pager']:undefined); return $t;
};
$.fn.createSearchDialog=function(gridOp,form,dialOp){ if($.isArray(gridOp)) gridOp={colModel:gridOp};
    var name=this.selector.replace("#",""), opD=$.extend({height:400,width:700,noTitleStuff:true,icon:'search',noOverflow:true},$.isObj(dialOp)?dialOp:{}), $t=this.createDialog(opD), fl=$t.find("form").length, id=name.replace("Dialog",""), container=$('<div class="condensed"><table id="'+id+'Grid"></table><div id="'+id+'GridPager"></div></div>'); if(fl===0) $t.append('<form></form>');
    var jform=$t.append(container).find("form").attr('id',id+"Form"); jform.find('fieldset').addClass('exa-fieldset').find('legend').addClass('Titulos2'); if($.vv(form)) jform.createFormSearch(form); var inp=jform.attr("action",jform.data('action')||"javascript:$.Search('"+id+"')").append('<input type="text" style="display:none" tabindex="-1" />').find("input[name='"+($.vv(form)&&$.vv(form['text'])?form['text']:'search')+"']").addClass("clearable").addClass("submit");
	var jgrid=$("#"+id+"Grid"),formHeight=jform.actual('outerHeight',{includeMargin:true}),gridHeight=opD['height']-formHeight-(opD['noTitleStuff']?95:65),op=$.extend({url:'',width:(opD['width']-32),height:gridHeight,postData:jform.getData(id+"Ajax"),colModel:[],rowNum:50,rowList:[10,20,50,100],autowidth:false,responsive:false,datatype:'local'},$.isObj(gridOp)?gridOp:{}); jgrid.createGrid(op,false,id+'GridPager',{view:false});
	var isHL=false; $.each(gridOp['colModel'],function(i,v){ if($.vv(v['classes']) && v['classes'].includes("highlightSearch")){ isHL=true; return false; } }); if(isHL) jgrid.on('jqGridAfterLoadComplete',function (ev,glc){ jgrid.highlightSearch(inp.val().trim()); });
	return $t;
};

$.fn.createSearchDialogPrecio=function(gridOp,form,dialOp){ if($.isArray(gridOp)) gridOp={colModel:gridOp};
    var name=this.selector.replace("#",""), opD=$.extend({height:400,width:700,noTitleStuff:true,icon:'search',noOverflow:true},$.isObj(dialOp)?dialOp:{}), $t=this.createDialog(opD), fl=$t.find("form").length, id=name.replace("Dialog",""), container=$('<div class="condensed"><table id="'+id+'Grid"></table><div id="'+id+'GridPager"></div></div>'); if(fl===0) $t.append('<form></form>');
    var jform=$t.append(container).find("form").attr('id',id+"Form"); jform.find('fieldset').addClass('exa-fieldset').find('legend').addClass('Titulos2'); if($.vv(form)) jform.createFormSearchPrecio(form); var inp=jform.attr("action",jform.data('action')||"javascript:$.Search('"+id+"')").append('<input type="text" style="display:none" tabindex="-1" />').find("input[name='"+($.vv(form)&&$.vv(form['text'])?form['text']:'search')+"']").addClass("clearable").addClass("submit");
    var jgrid=$("#"+id+"Grid"),formHeight=jform.actual('outerHeight',{includeMargin:true}),gridHeight=opD['height']-formHeight-(opD['noTitleStuff']?95:65),op=$.extend({url:'',width:(opD['width']-32),height:gridHeight,postData:jform.getData(id+"Ajax"),colModel:[],rowNum:50,rowList:[10,20,50,100],autowidth:false,responsive:false,datatype:'local'},$.isObj(gridOp)?gridOp:{}); jgrid.createGrid(op,false,id+'GridPager',{view:false});
    var isHL=false; $.each(gridOp['colModel'],function(i,v){ if($.vv(v['classes']) && v['classes'].includes("highlightSearch")){ isHL=true; return false; } }); if(isHL) jgrid.on('jqGridAfterLoadComplete',function (ev,glc){ jgrid.highlightSearch(inp.val().trim()); });
    return $t;
};
$.fn.unHighlightSearch=function(){ this.find('>tbody >tr[id] >td.highlightSearch >span.highlight').each(function(i,e){ $(e).replaceWith($(e).html()); }); };
$.fn.highlightSearch=function(va){ this.unHighlightSearch(); if($.vv(va) && va!==''){ va=va.split(" "); this.find('>tbody >tr[id] >td.highlightSearch').each(function(i,e){ $.each(va, function(j,v){ if(v!=='') $(e).html($(e).html().replace(new RegExp(v, "gi"),'<span class="highlight">$&</span>'));}); }); } };
$.createSearchDialog=function(name,colModel,height,width,title,grid,form){ var u; grid=$.isObj(grid)?grid:{}; grid['colModel']=colModel; return $('#'+name.replace("#","")).createSearchDialog(grid,form,{width:(width===null?u:width),height:height===null?u:height,noTitleStuff:title===null?u:title}); };
$.createSearchDialogPrecio=function(name,colModel,height,width,title,grid,form){ var u; grid=$.isObj(grid)?grid:{}; grid['colModel']=colModel; return $('#'+name.replace("#","")).createSearchDialogPrecio(grid,form,{width:(width===null?u:width),height:height===null?u:height,noTitleStuff:title===null?u:title}); };
$.Search=function(id){ var g=$("#"+id+"Grid"),f=$("#"+id+"Form"),e=g.getGridParam('postExtra')||{}; g.setGridParam({postData: null}); g.jqGrid('setGridParam',{datatype:'json',postData:$.extend(true,e,f.getData(id+"Ajax"))}).gridUpdate(1); f.effect("highlight",{},500); };
$.SearchOrDialog=function(name,callback,otherForm){ if($.isObj(otherForm)){$.SearchOrDialogArray(name,callback,otherForm); return;}; name=name.replace("#","");var id=name.replace("Dialog",""); var jformtemp=$(($.vv(otherForm)?otherForm:"#"+id+"FormTemp")),postdata=$.extend(jformtemp.getData(id+"Ajax"),{page:1,rows:2}); jformtemp.effect("highlight",{},500); var field=jformtemp.find('.dialogSearch');  $.SearchOrDialogArray(name,callback,postdata,(field.length>0?field.attr('name'):null)); };
$.SearchOrDialogArray=function(name,callback,array,field){ field=field||'search'; name=name.replace("#","");var id=name.replace("Dialog",""); var jgrid=$("#"+id+"Grid"),postdata=$.extend($("#"+id+"Form").getData(id+"Ajax"),array,{page:1,rows:2}); $.get(jgrid[0].p.url,postdata, function(response){ if(parseInt(response['records'])===1){callback(response['rows'][0]);}else{$("#"+id+"Form").find("input[name='"+field+"']").addClass('x').val(postdata[field]);$.Search(id);$("#"+name).dialog("open");} },'json'); };
$.getDialogGrid=function(name){var id=name.replace("Dialog","");return $(id+"Grid");};
$.fn.getDialogGrid=function(){if(this.length===1){ if($.vv(this.attr('role'))) return this; var id=this.attr('id').replace("Dialog","");return $('#'+id+"Grid");} return null;};
$.alert=function(message,action,icon){
	if(typeof Swal!=='undefined'){
		var iconMap={'ok':'success','remove':'error','alert':'warning','info-sign':'info','info':'info'};
		var swalIcon=iconMap[icon]||icon||'info';
		message=message||'El Servidor ha fallado en responder!';
		Swal.fire({title:'MENSAJE DEL SISTEMA',html:'<b>'+message+'</b>',icon:swalIcon,confirmButtonText:'Aceptar',customClass:{confirmButton:'btn btn-primary'},buttonsStyling:false}).then(function(){if($.vv(action))action();});
	}else{
		icon=icon||($.vv(message)?'info-sign':'alert');message=message||'El Servidor ha fallado en responder!'; var dialog=$('<div title="MENSAJE DEL SISTEMA">'+'<div style="font-size:14px;"><center><b>'+message+'</b></center></div></div>');
		dialog.dialog({
		  dialogClass: 'dialog-alert-test', closeText:"Cerrar Mensaje", modal: true,autoOpen: true,resizable: false,position:{my: "center",at: "center",of: $('body')}, buttons: [{text: "Aceptar",click:function(){$(this).dialog( "close" );}, icons:{ primary: "ui-icon-check" }}],
		  close: function(){$($(this).parent()[0].nextSibling).unbind('click');$(this).remove();if($.vv(action))action();},show: {effect: "fade",duration: 500},
		  open: function(){ var dg=$(this); $(dg.parent()[0].nextSibling).bind('click', function (){ dg.dialog('close'); });}
		}).parent().children(".ui-dialog-titlebar").prepend($.createIcon(icon)); return false;
	}
};
$.fn.alertDiv= function(msg,animate,time){
	msg=msg||{header:'SISTEMA:',message:'No se pudo completar la acci&oacute;n.',type:2,max:1,unique:true}; msg.type=msg.type||2;var type='danger';msg.max=msg.max||1;msg.unique=($.vv(msg.unique)?msg.unique:true);time=time||5000;var id='alert_id_'+(Math.round(Math.random() * 99999)).toString(),timeExtra=550;animate=animate||false;
	var mensaje=$('<div id="'+id+'" class="msg alert fade in '+(animate?"animated bounceIn":'')+'"><a href="#" class="close" data-dismiss="alert">'+$.createIcon('remove')+'</a>'+(!$.vv(msg.header)?'':'<strong>'+msg.header+'</strong>&nbsp;')+(!$.vv(msg.message)?'':msg.message)+'</div>');
	if(!isNaN(msg.type)){switch(msg.type){ case 0:type='success';break; case 1:type='info';break; }}else{type=msg.type;}
	mensaje.addClass( "alert-"+type );//mensaje.show( 'fade', {}, 500, null );
	if(msg.unique){this.find('.msg').remove();this.append(mensaje);}
	else{
		this.prepend(mensaje);var others=this.find('.msg');
		if(others.length>=msg.max)
			for(var i=(msg.max);i<others.length;i++)
				if(animate){$(others[i]).addClass( "fadeOutDown" ).css('position','absolute').removeClass('msg');var otherId=$(others[i]).attr('id');setTimeout(function(){if($('#'+otherId).length) $('#'+otherId).remove();},timeExtra);}
				else{$(others[i]).hide().remove();}
	}//mensaje.hide(); mensaje.show( 'fade', {}, 500, null );
	if(animate) setTimeout(function(){if($('#'+id).length){$('#'+id).addClass( "fadeOutDown" ).css('position','absolute').removeClass('msg');setTimeout(function(){$('#'+id).remove();},timeExtra);}},time);
	else {setTimeout(function(){if($('#'+id).length){$('#'+id).hide().remove();}},time);}
};
$.fn.alertMsg= function(message){ var $div=this.parent().parent().find('.msgDiv'); if(!$div.length){$div=this.parent().parent().parent().find('.msgDiv');} if(!$.vv(message)){ $div.find('.lblMsg').html(''); $div.find('.imgMsg').attr('src','../../mascaras/model1/imagenes/ok-s.gif'); }else{ $div.find('.lblMsg').html(message); $div.find('.imgMsg').attr('src','../../mascaras/model1/imagenes/32x32/cancel.gif'); }return this; };
$.fn.clearMsg=function(){ var $div=this.parent().parent().find('.msgDiv'); if(!$div.length){$div=this.parent().parent().parent().find('.msgDiv');} $div.find('.lblMsg').html('');	$div.find('.imgMsg').removeAttr('src');	return this; };
//FUNCIONES GENERALES
function setfocus(campo){if(campo){campo.focus();}}
function onNumeric(e,reg){var k=(document.all)?e.keyCode:e.which,te=String.fromCharCode(k); if(k===13||k===8) return !0; if(te==='.'&&e.target.value.indexOf('.')>=0) return !1; var u,t=this,i=t!==u&&t.tagName==='INPUT',d=i?t.getAttribute('decimals'):null,n=i?t.getAttribute('negative'):null; if(i){ t.dataset.previus_value=t.value; } return new RegExp(reg||('^[0-9'+(d!==null?'\.':'')+(n!==null?'\-':'')+']*$'), 'gi').test(te); }
function onPasteInput(){var u,t=this,i=t!==u&&t.tagName==='INPUT'; if(i)t.dataset.previus_value=t.value; }
function onIsNaN(e){var u,t=this,i=t!==u&&t.tagName==='INPUT',v=e.target.value,pv=i?t.dataset.previus_value||'':'',n=i?t.getAttribute('negative'):null,d=i?t.getAttribute('decimals'):null; if(i)delete(t.dataset.previus_value); if((isNaN(v)&&(!i||!(i&&n!==null&&v==='-'))) ||(i&&d===null&&v.indexOf('.')>=0)||(i&&n===null&&v*1<0))t.value=pv; if(i&&d!==null&&d!==''&&v.indexOf('.')>=0){ var dec=String(v).split("."); if(dec[1].length>d*1) t.value=dec[0]+'.'+dec[1].substring(0,d); } }
function ejecutaOnEnter(e,v){if(e==='enter'||e.keyCode===13){ try{ var f=eval($(this).data('onenter')); if($.isFunc(f)) f.call($(this),v); }catch(e){} } }
function validar_injections(e){var te=(document.all)?e.keyCode:e.which; if(te===13||te===8)return !0; return /[A-Za-z0-9\u00f1\u00d1\u00e0-\u00fc_\+\/#~&\-.:\$\%\ \[\]\(\)]/.test(String.fromCharCode(te)); }
function validar_numeric(e){return onNumeric.call(this,e,'^[0-9]*$');}
function validar_decimal(e){return onNumeric.call(this,e,'^[0-9\.]*$');}
Number.prototype.padLeft=function(n,str){return (this<0?'-':'')+Array(n-String(Math.abs(this)).length+1).join(str||'0')+Math.abs(this);};
Number.prototype.padRight=function(n,str){return (this<0?'-':'')+Math.abs(this)+Array(n-String(Math.abs(this)).length+1).join(str||'0');};
Number.prototype.ordinal=function(fem,type){var num=this,end=fem===true?'a':"o", mod1 = num%100, mod2 = num%10, ord; if((mod1-mod2) === 10){ ord = "m"+end; }else{ switch(mod2){ case 1: ord=fem===true?'ra':"er"; break; case 2: ord="d"+end; break; case 3: ord=fem===true?'ra':"er"; break; case 4:case 5:case 6: ord="t"+end; break; case 8: ord="v"+end; break;case 9: ord="n"+end; break; case 7: default: ord="m"+end; break; } } switch(type){case "sub":return num+"<sub>"+ord+"<\/sub>"; case "sup":return num+"<sup>"+ord+"<\/sup>";default:return num+ord;}};
String.prototype.upperFirstChar=function(){return this.length>1?(this.substring(0,1).toUpperCase())+this.slice(1):(this.length===0?this:this.toUpperCase());};
String.prototype.upperFirstWords=function(){return this.length>1?this.toLowerCase().replace(/(^| )(\w)/g, function(s){return s.toUpperCase();}):(this.length===0?this:this.toUpperCase());};
String.prototype.toNum=function(){return $.isNum(this)?(this)*1:0;}; Number.prototype.toNum=function(){return this*1;};
function ek(a){if($.isObj(a)){a.toNum=function(k){return this.hasOwnProperty(k)&&['number','string'].indexOf(typeof this[k])>-1?this[k].toNum():0;};a.to=function(k,d){return this.hasOwnProperty(k)?this[k]:d||'';};}return a;};
// CREDITO DEBITO DIARIO
$.fn.updateGridDiario=function(){
    var total_haber=0,total_debe=0;
    var ids= this.jqGrid('getDataIDs');
    for(var i=0;i<ids.length;i++){
        var tip=this.jqGrid('getCell',ids[i],'Det_Tip'), monto;
        if(tip==='D'){monto=$('#'+ids[i]+'_Debe');total_debe +=Number(monto.val());}
        else {monto=$('#'+ids[i]+'_Haber');total_haber +=Number(monto.val());}
        if(!parseFloat(monto.val())){monto.val("");}
    };
    this.jqGrid("footerData", "set", {Glosa: "<div style='text-align:right;'>TOTALES:</div>", Debe:total_debe, Haber:total_haber});
    if(this.data('Diff')===true) $('#'+this.attr('id')+'_diferencia').val($.toFixed(Math.abs(total_debe-total_haber)));
    if($.isText(this.data('Com_Val'))) $(this.data('Com_Val')).val($.toFixed(total_debe));
};
$.fn.createInputDiario=function(element,tipo){
    var jgrid=this, rowId=$(element).closest('tr.jqgrow').attr('id'), tip=jgrid.jqGrid('getCell',rowId,'Det_Tip');
    $(element).parent().removeAttr("title");
    if(tip===tipo){
        $(element).on('change', function(){ $(this).val($.toFixed($(this).val())); jgrid.updateGridDiario();});
        $(element).attr('onkeypress','return  validar_decimal(event)');
        if(parseFloat($(element).val())===0) $(element).val("");
        $(element).css('text-align', 'right').focus();
    }else{ $(element).parent().html(''); };
};
$.clearFooterDiario=function(grid,diff,com_val){ $(grid).data('Com_Val',com_val); $(grid).data('Diff',diff); grid=grid.replace("#","");
    if(diff===true) $("#gbox_"+grid+" #gview_"+grid+" div.ui-jqgrid-titlebar").append("<div class='pull-right'>Diferencia:&nbsp;<input id='"+grid+"_diferencia' value='0.00' style='width: 100px; color: black; margin-top: -2px; text-align:right;height: 18px;' tabindex='-1' readonly='' />&nbsp;<div>");
	var $footRow=$("#gbox_"+grid+" #gview_"+grid+" .ui-jqgrid-sdiv .footrow");
    $footRow.find('>td[aria-describedby]:not(:first-child)').css({"border-right-color":"transparent","background-color":"white"});
	$footRow.find('>td[aria-describedby="'+grid+'_Debe"],>td[aria-describedby="'+grid+'_Haber"]').css({"border-right-color":"","background-color":''});
    $footRow.find('>td[aria-describedby="'+grid+'_Glosa"]').css("border-right-color", "");
};
/* Copyright 2012, Ben Lin
 * http://dreamerslab.com/blog/en/get-hidden-elements-width-and-height-with-jquery/
 * Version: 1.0.16
 */
(function(a){a.fn.addBack=a.fn.addBack||a.fn.andSelf;a.fn.extend({actual:function(b,l){if(!this[b]){throw'$.actual => The jQuery method "'+b+'" you called does not exist';}var f={absolute:false,clone:false,includeMargin:false};
var i=a.extend(f,l);var e=this.eq(0);var h,j;if(i.clone===true){h=function(){var m="position: absolute !important; top: -1000 !important; ";e=e.clone().attr("style",m).appendTo("body");};j=function(){e.remove();};}else{var g=[];var d="";var c;h=function(){c=e.parents().addBack().filter(":hidden");d+="visibility: hidden !important; display: block !important; ";
if(i.absolute===true){d+="position: absolute !important; ";}c.each(function(){var m=a(this);var n=m.attr("style");g.push(n);m.attr("style",n?n+";"+d:d);});};j=function(){c.each(function(m){var o=a(this);var n=g[m];if($.isUnd(n)){o.removeAttr("style");}else{o.attr("style",n);}});};}h();var k=/(outer)/.test(b)?e[b](i.includeMargin):e[b]();j();return k;}});})(jQuery);
// CLONE ADDON
!function(e){jQuery.fn.clone=function(){for(var t=e.apply(this,arguments),n="textarea",d="select",i=this.find(n).add(this.filter(n)),f=t.find(n).add(t.filter(n)),l=this.find(d).add(this.filter(d)),r=t.find(d).add(t.filter(d)),a=0,s=i.length;s>a;++a)$(f[a]).val($(i[a]).val());for(var a=0,s=l.length;s>a;++a)r[a].selectedIndex=l[a].selectedIndex;return t;};}(jQuery.fn.clone);
// CLEARABLE INPUT - Pone un boton X para limpiar un campo de busqueda
jQuery(function($){ function tog(v){return v?'addClass':'removeClass';}
  $(document).on('input', '.clearable', function(){$(this)[tog(this.value)]('x');})
  .on('mousemove', '.x', function(e){$(this)[tog(this.offsetWidth-18 < e.clientX-this.getBoundingClientRect().left)]('onX');})
  .on('touchstart click', '.onX', function(ev){ev.preventDefault();$(this).removeClass('x onX').val('').trigger('keyup').trigger('change').trigger('clearable'); if($(this).hasClass("onEnter"))ejecutaOnEnter.call(this,'enter',this.value); if($(this).hasClass("submit"))this.form.submit(); });
});
/*
$.topZIndex=function (selector){return Math.max(0, Math.max.apply(null, $.map(((selector || "*")==="*")? $.makeArray(document.getElementsByTagName("*")) : $(selector),function (v){return parseFloat($(v).css("z-index")) || null;})));};//Returns the highest (top-most) zIndex in the document(minimum value returned: 0)
$.fn.topZIndex=function(opt){ if(this.length===0) return this; opt=$.extend({increment: 1}, opt); var zmax=$.topZIndex(opt.selector), inc=opt.increment;return this.each(function (){ this.style.zIndex=(zmax += inc); });}; //Increments the CSS z-index of each element in the matched set to a value larger than the highest current zIndex in the document.
$.fn.topZItem=function(){ var itemMax; this.each(function(){ var index_current=parseInt($(this).css("zIndex"), 10),index_highest=($.vv(itemMax)?parseInt($(itemMax).css("zIndex"), 10):0); if(index_current >index_highest){itemMax=this;} }); return $(itemMax);}; // devuelve el item con mas alto zindex
*/
 // Convierte un form en un objeto array
$.fn.serializeObject=function(){ var o={},a=this.serializeArray(); $.each(a,function(){ if(!$.isUnd(o[this.name])){ if(!o[this.name].push){o[this.name]=[o[this.name]];} o[this.name].push(this.value||'');}else{o[this.name]=this.value||'';} }); return o; };
// TOGGLE ATTRIBUTE CSS
$.fn.toggleAttr=function(attr){ var $this=$(this); if(!$.vv(attr)) return $this; $this.each(function(){ var $t=$(this); $t.attr(attr)?$t.removeAttr(attr):$t.attr(attr, attr); }); return $this;};
$.fn.toggleStyles=function(css,style1,style2){if(!$.vv(css)||!$.vv(style1)||!$.vv(style2)) return this; var $this=$(this), cssStyle={}; ($this.css(css)===style1)?cssStyle[css]=style2:cssStyle[css]=style1; $this.css(cssStyle); return $this;};
$.fn.toggleCss=function(css,style){return $(this).toggleStyles(css,style,'');};

$.hoy=function(){ return $.datepicker.formatDate('yy-mm-dd', new Date()); };
$.isset=function(name){ if(!$.isText(name)) return false; try{eval(name);}catch(e){ if(e instanceof ReferenceError) return false; } return true; };
$.isEmpty=function(v){ if(!arguments.length) throw 'No Argument!'; return (!$.vv(v))||($.isBool(v)&&v===false)||($.isText(v)&&v.trim()==='')||($.isArray(v)&&v.length===0)||($.isObj(v)&&Object.keys(v).length===0)||($.isNum(v)&&v===0); };
$.ifEmpty=function(v,d){ return $.isEmpty(v)?d||null:v; };
$.ifvv=function(v,d){ return $.vv(v)?v:d||null; };
$.isUnd=function(v){ return v===undefined; };
$.varValid=$.vv=function(v){return (v!==null && !$.isUnd(v));};
$.isBoolean=$.isBool=function(v){return typeof v==='boolean';};
$.isString=$.isText=function(v){return typeof v==='string';};
$.isNum=$.isNumeric; $.isFunc=$.isFunction;
$.toNum=function(s){return $.isNum(s)?s*1:0;};
$.isObject=$.isObj=function(v){return $.vv(v)&&!$.isArray(v)&&typeof v==='object';};
$.dateValid=function(fecha){ if(!$.isText(fecha)||fecha.length!==10) return false; var f=/^(\d{4})[-\/](\d{2})[-\/](\d{2})$/.exec(fecha); if(f===null) return false; var d=f[3], m=f[2], y=f[1]; return m>0 && m<13 && y>1899 && y<32768 && d>0 && d<=(new Date(y,m,0)).getDate(); };
$.round=function(val,dec){ dec=$.vv(dec)?dec:2; if(!$.vv(val)||isNaN(val)||isNaN(dec)) return null; return (Math.round(val*Math.pow(10,dec))/Math.pow(10,dec)); };
$.toFixed=function(val,dec){ dec=$.vv(dec)?dec:2; var n=$.round(val,dec); return ($.vv(n)?n.toFixed(dec):null); };
$.strHtmlToStr=function(v,all){ if(!$.vv(v)) return ''; all=($.isBool(all)?all:false); var $o=$('<span>'); if($.isText(v)){ if(all) return $o.html(v).text(); else  return $o.html(v).children().remove().end().text(); }else{ if(all) return $o.append(v.clone()).text(); else return $o.append(v.clone()).children().remove().end().text(); } };
$.jsonParser=function(v){if($.isArray(v)||$.isObj(v)){return JSON.stringify(v);}else{try{return JSON.parse(v);}catch(e){return v;}}};
$.cloneData =function(v){if(!$.vv(v)) return v; if($.isArray(v))return $.extend(true,[],v); if($.isObj(v))return $.extend(true,{},v); return v;};
$.toBool=function(val){ if(!$.vv(val))return false; if($.isBool(val))return val; var num=+val,b=false;if(!isNaN(num)) b=!!num; else switch(String(val).toLowerCase()){	/*case 'y': case 'yes': case 's': case 'si': b=true; break;*/ case 'n': case 'no': case 'f': case 'off': case 'apagado': b=false; break; default: b=!!String(val).toLowerCase().replace(!!0,'');}return b;};
$.getDateRegExp=function(regex){ var re='(?:19|20)[0-9]{2}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1[0-9]|2[0-9])|(?:(?!02)(?:0[1-9]|1[0-2])-(?:30))|(?:(?:0[13578]|1[02])-31))'; return(regex===true?new RegExp(re):re); };
$.getHoraRegExp=function(){ return '([0-1]{1}[0-9]{1}|20|21|22|23):[0-5]{1}[0-9]{1}'; };
$.setLocalStore=function(name,data){ localStorage.setItem(name, $.jsonParser(data)); if($.isUnd(data)) localStorage.removeItem(name); };
$.getLocalStore=function(name){ var data=localStorage.getItem(name); if($.varValid(data)) return $.jsonParser(data); };
$.getCookie=function(cname){ var na=cname+"=",dc=decodeURIComponent(document.cookie),ca=dc.split(';');for(var i=0;i<ca.length;i++){ var c=ca[i]; while(c.charAt(0)===' '){c=c.substring(1);} if(c.indexOf(na)===0){return c.substring(na.length, c.length);} } return ""; };
$.removeCookie=function(key,value){ var t = new Date();	t.setMilliseconds(t.getMilliseconds() + -1 * 864e+5); document.cookie=[encodeURIComponent(key),'=',String(value),'; expires=' + t.toUTCString()].join(''); };
/* require jquer.validate */
//$.clearValidate=function(){$.validator.prototype.showErrors=function(){}; $.validator.setDefaults({debug:false,onsubmit:false});};
// VALIDACION CUSTOM - Reemplaza popups nativos del navegador con SweetAlert2
$(document).on('invalid','input[required],select[required],textarea[required],input[pattern],select[pattern],textarea[pattern]',function(e){
	e.preventDefault();e.stopImmediatePropagation();
	var $t=$(this),msg=$t.data('msg'),tag=$t[0].tagName.toUpperCase();
	if(!msg){
		var nombre=$t.attr('placeholder')||$t.attr('name')||'Este campo';
		if($t.attr('required')) msg='El campo "'+nombre+'" es obligatorio.';
		else if($t.attr('pattern')) msg='El campo "'+nombre+'" tiene un formato invalido.';
		else msg='El campo "'+nombre+'" es invalido.';
	}
	if(typeof Swal!=='undefined'){
		Swal.fire({title:'Validacion',html:'<b>'+msg+'</b>',icon:'warning',confirmButtonText:'Aceptar',customClass:{confirmButton:'btn btn-primary'},buttonsStyling:false}).then(function(){$t.focus();});
	}else if(typeof $.alert==='function'){
		$.alert(msg,function(){$t.focus();},'warning');
	}else{
		alert(msg);$t.focus();
	}
	return false;
});
$(document).on('submit','form',function(e){
	var $form=$(this),invalidos=[];
	$form.find('input[required],select[required],textarea[required],input[pattern],select[pattern],textarea[pattern]').each(function(){
		var $t=$(this),val=$t.val();
		if($t.attr('required')&&(val===undefined||val===null||$.trim(val)==='')) invalidos.push($t);
		else if($t.attr('pattern')&&val&&!new RegExp($t.attr('pattern')).test(val)) invalidos.push($t);
	});
	if(invalidos.length>0){
		e.preventDefault();e.stopImmediatePropagation();
		var $primero=invalidos[0],msg=$primero.data('msg');
		if(!msg){
			var nombre=$primero.attr('placeholder')||$primero.attr('name')||'Este campo';
			if($primero.attr('required')) msg='El campo "'+nombre+'" es obligatorio.';
			else msg='El campo "'+nombre+'" tiene un formato invalido.';
		}
		if(typeof Swal!=='undefined'){
			Swal.fire({title:'Validacion',html:'<b>'+msg+'</b>',icon:'warning',confirmButtonText:'Aceptar',customClass:{confirmButton:'btn btn-primary'},buttonsStyling:false}).then(function(){$primero.focus();});
		}else if(typeof $.alert==='function'){
			$.alert(msg,function(){$primero.focus();},'warning');
		}else{
			alert(msg);$primero.focus();
		}
		return false;
	}
});